// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="LUT_accel_LUT_accel,hls_ip_2020_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.400000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.672000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=1822,HLS_SYN_LUT=2032,HLS_VERSION=2020_2_2}" *)

module LUT_accel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        stream_in_TDATA,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_in_TID,
        stream_in_TDEST,
        stream_out_TDATA,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        stream_out_TID,
        stream_out_TDEST,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 11;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [23:0] stream_in_TDATA;
input  [2:0] stream_in_TKEEP;
input  [2:0] stream_in_TSTRB;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
input  [0:0] stream_in_TID;
input  [0:0] stream_in_TDEST;
output  [23:0] stream_out_TDATA;
output  [2:0] stream_out_TKEEP;
output  [2:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
output  [0:0] stream_out_TID;
output  [0:0] stream_out_TDEST;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] rows;
wire   [31:0] cols;
wire   [7:0] lut_q0;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write;
wire   [31:0] Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_din;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_write;
wire   [31:0] Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_din;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_write;
wire   [31:0] Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_din;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_write;
wire   [31:0] Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_din;
wire    Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_write;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready;
wire   [23:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_write;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_stream_in_TREADY;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read;
wire   [31:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write;
wire   [31:0] AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write;
wire    LUT_9_1080_1920_1_U0_ap_start;
wire    LUT_9_1080_1920_1_U0_ap_done;
wire    LUT_9_1080_1920_1_U0_ap_continue;
wire    LUT_9_1080_1920_1_U0_ap_idle;
wire    LUT_9_1080_1920_1_U0_ap_ready;
wire    LUT_9_1080_1920_1_U0_img_in_419_read;
wire   [23:0] LUT_9_1080_1920_1_U0_img_out_420_din;
wire    LUT_9_1080_1920_1_U0_img_out_420_write;
wire   [9:0] LUT_9_1080_1920_1_U0_lut_address0;
wire    LUT_9_1080_1920_1_U0_lut_ce0;
wire    LUT_9_1080_1920_1_U0_p_src_rows_read;
wire    LUT_9_1080_1920_1_U0_p_src_cols_read;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_img_out_420_read;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read;
wire   [23:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDATA;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TVALID;
wire   [2:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TKEEP;
wire   [2:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TSTRB;
wire   [0:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TUSER;
wire   [0:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TLAST;
wire   [0:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TID;
wire   [0:0] xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDEST;
wire    ap_sync_continue;
wire    img_in_rows_c_full_n;
wire   [31:0] img_in_rows_c_dout;
wire    img_in_rows_c_empty_n;
wire    img_in_cols_c_full_n;
wire   [31:0] img_in_cols_c_dout;
wire    img_in_cols_c_empty_n;
wire    img_out_rows_c_full_n;
wire   [31:0] img_out_rows_c_dout;
wire    img_out_rows_c_empty_n;
wire    img_out_cols_c_full_n;
wire   [31:0] img_out_cols_c_dout;
wire    img_out_cols_c_empty_n;
wire    img_in_data_full_n;
wire   [23:0] img_in_data_dout;
wire    img_in_data_empty_n;
wire    img_in_rows_c9_full_n;
wire   [31:0] img_in_rows_c9_dout;
wire    img_in_rows_c9_empty_n;
wire    img_in_cols_c10_full_n;
wire   [31:0] img_in_cols_c10_dout;
wire    img_in_cols_c10_empty_n;
wire    img_out_data_full_n;
wire   [23:0] img_out_data_dout;
wire    img_out_data_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
wire    ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
reg    ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready;
wire    ap_sync_LUT_9_1080_1920_1_U0_ap_ready;
wire   [0:0] start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din;
wire    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n;
wire   [0:0] start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout;
wire    start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n;
wire   [0:0] start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din;
wire    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n;
wire   [0:0] start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout;
wire    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_start_full_n;
wire    AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write;
wire    LUT_9_1080_1920_1_U0_start_full_n;
wire    LUT_9_1080_1920_1_U0_start_write;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n;
wire    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready = 1'b0;
end

LUT_accel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .rows(rows),
    .cols(cols),
    .lut_address0(LUT_9_1080_1920_1_U0_lut_address0),
    .lut_ce0(LUT_9_1080_1920_1_U0_lut_ce0),
    .lut_q0(lut_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

LUT_accel_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start),
    .start_full_n(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n),
    .ap_done(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_done),
    .ap_continue(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue),
    .ap_idle(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle),
    .ap_ready(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready),
    .start_out(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_out),
    .start_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .rows(rows),
    .cols(cols),
    .img_in_rows_out_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_din),
    .img_in_rows_out_full_n(img_in_rows_c_full_n),
    .img_in_rows_out_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_write),
    .img_in_cols_out_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_din),
    .img_in_cols_out_full_n(img_in_cols_c_full_n),
    .img_in_cols_out_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_write),
    .img_out_rows_out_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_din),
    .img_out_rows_out_full_n(img_out_rows_c_full_n),
    .img_out_rows_out_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_write),
    .img_out_cols_out_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_din),
    .img_out_cols_out_full_n(img_out_cols_c_full_n),
    .img_out_cols_out_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_write)
);

LUT_accel_AXIvideo2xfMat_24_9_1080_1920_1_s AXIvideo2xfMat_24_9_1080_1920_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start),
    .ap_done(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_done),
    .ap_continue(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue),
    .ap_idle(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle),
    .ap_ready(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready),
    .img_in_419_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_din),
    .img_in_419_full_n(img_in_data_full_n),
    .img_in_419_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_write),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TVALID(stream_in_TVALID),
    .stream_in_TREADY(AXIvideo2xfMat_24_9_1080_1920_1_U0_stream_in_TREADY),
    .stream_in_TKEEP(stream_in_TKEEP),
    .stream_in_TSTRB(stream_in_TSTRB),
    .stream_in_TUSER(stream_in_TUSER),
    .stream_in_TLAST(stream_in_TLAST),
    .stream_in_TID(stream_in_TID),
    .stream_in_TDEST(stream_in_TDEST),
    .img_1_dout(img_in_rows_c_dout),
    .img_1_empty_n(img_in_rows_c_empty_n),
    .img_1_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read),
    .img_2_dout(img_in_cols_c_dout),
    .img_2_empty_n(img_in_cols_c_empty_n),
    .img_2_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read),
    .img_1_out_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din),
    .img_1_out_full_n(img_in_rows_c9_full_n),
    .img_1_out_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write),
    .img_2_out_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din),
    .img_2_out_full_n(img_in_cols_c10_full_n),
    .img_2_out_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write)
);

LUT_accel_LUT_9_1080_1920_1_s LUT_9_1080_1920_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(LUT_9_1080_1920_1_U0_ap_start),
    .ap_done(LUT_9_1080_1920_1_U0_ap_done),
    .ap_continue(LUT_9_1080_1920_1_U0_ap_continue),
    .ap_idle(LUT_9_1080_1920_1_U0_ap_idle),
    .ap_ready(LUT_9_1080_1920_1_U0_ap_ready),
    .img_in_419_dout(img_in_data_dout),
    .img_in_419_empty_n(img_in_data_empty_n),
    .img_in_419_read(LUT_9_1080_1920_1_U0_img_in_419_read),
    .img_out_420_din(LUT_9_1080_1920_1_U0_img_out_420_din),
    .img_out_420_full_n(img_out_data_full_n),
    .img_out_420_write(LUT_9_1080_1920_1_U0_img_out_420_write),
    .lut_address0(LUT_9_1080_1920_1_U0_lut_address0),
    .lut_ce0(LUT_9_1080_1920_1_U0_lut_ce0),
    .lut_q0(lut_q0),
    .p_src_rows_dout(img_in_rows_c9_dout),
    .p_src_rows_empty_n(img_in_rows_c9_empty_n),
    .p_src_rows_read(LUT_9_1080_1920_1_U0_p_src_rows_read),
    .p_src_cols_dout(img_in_cols_c10_dout),
    .p_src_cols_empty_n(img_in_cols_c10_empty_n),
    .p_src_cols_read(LUT_9_1080_1920_1_U0_p_src_cols_read)
);

LUT_accel_xfMat2AXIvideo_24_9_1080_1920_1_s xfMat2AXIvideo_24_9_1080_1920_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start),
    .ap_done(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done),
    .ap_continue(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue),
    .ap_idle(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle),
    .ap_ready(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready),
    .img_out_420_dout(img_out_data_dout),
    .img_out_420_empty_n(img_out_data_empty_n),
    .img_out_420_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_out_420_read),
    .img_1_dout(img_out_rows_c_dout),
    .img_1_empty_n(img_out_rows_c_empty_n),
    .img_1_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read),
    .img_2_dout(img_out_cols_c_dout),
    .img_2_empty_n(img_out_cols_c_empty_n),
    .img_2_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read),
    .stream_out_TDATA(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDATA),
    .stream_out_TVALID(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TVALID),
    .stream_out_TREADY(stream_out_TREADY),
    .stream_out_TKEEP(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TKEEP),
    .stream_out_TSTRB(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TSTRB),
    .stream_out_TUSER(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TUSER),
    .stream_out_TLAST(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TLAST),
    .stream_out_TID(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TID),
    .stream_out_TDEST(xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDEST)
);

LUT_accel_fifo_w32_d2_S img_in_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_din),
    .if_full_n(img_in_rows_c_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_rows_out_write),
    .if_dout(img_in_rows_c_dout),
    .if_empty_n(img_in_rows_c_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_read)
);

LUT_accel_fifo_w32_d2_S img_in_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_din),
    .if_full_n(img_in_cols_c_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_in_cols_out_write),
    .if_dout(img_in_cols_c_dout),
    .if_empty_n(img_in_cols_c_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_read)
);

LUT_accel_fifo_w32_d4_S img_out_rows_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_din),
    .if_full_n(img_out_rows_c_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_rows_out_write),
    .if_dout(img_out_rows_c_dout),
    .if_empty_n(img_out_rows_c_empty_n),
    .if_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_1_read)
);

LUT_accel_fifo_w32_d4_S img_out_cols_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_din),
    .if_full_n(img_out_cols_c_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_img_out_cols_out_write),
    .if_dout(img_out_cols_c_dout),
    .if_empty_n(img_out_cols_c_empty_n),
    .if_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_2_read)
);

LUT_accel_fifo_w24_d2_S img_in_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_din),
    .if_full_n(img_in_data_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_in_419_write),
    .if_dout(img_in_data_dout),
    .if_empty_n(img_in_data_empty_n),
    .if_read(LUT_9_1080_1920_1_U0_img_in_419_read)
);

LUT_accel_fifo_w32_d2_S img_in_rows_c9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_din),
    .if_full_n(img_in_rows_c9_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_1_out_write),
    .if_dout(img_in_rows_c9_dout),
    .if_empty_n(img_in_rows_c9_empty_n),
    .if_read(LUT_9_1080_1920_1_U0_p_src_rows_read)
);

LUT_accel_fifo_w32_d2_S img_in_cols_c10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_din),
    .if_full_n(img_in_cols_c10_full_n),
    .if_write(AXIvideo2xfMat_24_9_1080_1920_1_U0_img_2_out_write),
    .if_dout(img_in_cols_c10_dout),
    .if_empty_n(img_in_cols_c10_empty_n),
    .if_read(LUT_9_1080_1920_1_U0_p_src_cols_read)
);

LUT_accel_fifo_w24_d2_S img_out_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(LUT_9_1080_1920_1_U0_img_out_420_din),
    .if_full_n(img_out_data_full_n),
    .if_write(LUT_9_1080_1920_1_U0_img_out_420_write),
    .if_dout(img_out_data_dout),
    .if_empty_n(img_out_data_empty_n),
    .if_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_img_out_420_read)
);

LUT_accel_start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0 start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din),
    .if_full_n(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .if_dout(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_dout),
    .if_empty_n(start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n),
    .if_read(AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_ready)
);

LUT_accel_start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0 start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din),
    .if_full_n(start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n),
    .if_write(Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_write),
    .if_dout(start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout),
    .if_empty_n(start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n),
    .if_read(xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready <= ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready <= ap_sync_LUT_9_1080_1920_1_U0_ap_ready;
        end
    end
end

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_continue = 1'b1;

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_start = start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_empty_n;

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_start_full_n = 1'b1;

assign AXIvideo2xfMat_24_9_1080_1920_1_U0_start_write = 1'b0;

assign Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_continue = 1'b1;

assign Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_start = ((ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_start_full_n = (start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n & start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_full_n);

assign LUT_9_1080_1920_1_U0_ap_continue = 1'b1;

assign LUT_9_1080_1920_1_U0_ap_start = ((ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready ^ 1'b1) & ap_start);

assign LUT_9_1080_1920_1_U0_start_full_n = 1'b1;

assign LUT_9_1080_1920_1_U0_start_write = 1'b0;

assign ap_done = xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done;

assign ap_idle = (xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle & LUT_9_1080_1920_1_U0_ap_idle & Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_idle & AXIvideo2xfMat_24_9_1080_1920_1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready = (ap_sync_reg_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready | Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready);

assign ap_sync_LUT_9_1080_1920_1_U0_ap_ready = (ap_sync_reg_LUT_9_1080_1920_1_U0_ap_ready | LUT_9_1080_1920_1_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done;

assign ap_sync_ready = (ap_sync_LUT_9_1080_1920_1_U0_ap_ready & ap_sync_Block_ZN2xf2cv3MatILi9ELi1080ELi1920ELi1ELi2EEC2Eii_exit1_proc_U0_ap_ready);

assign start_for_AXIvideo2xfMat_24_9_1080_1920_1_U0_din = 1'b1;

assign start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din = 1'b1;

assign stream_in_TREADY = AXIvideo2xfMat_24_9_1080_1920_1_U0_stream_in_TREADY;

assign stream_out_TDATA = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDATA;

assign stream_out_TDEST = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TDEST;

assign stream_out_TID = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TID;

assign stream_out_TKEEP = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TKEEP;

assign stream_out_TLAST = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TLAST;

assign stream_out_TSTRB = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TSTRB;

assign stream_out_TUSER = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TUSER;

assign stream_out_TVALID = xfMat2AXIvideo_24_9_1080_1920_1_U0_stream_out_TVALID;

assign xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue = 1'b1;

assign xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start = start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n;

assign xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n = 1'b1;

assign xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write = 1'b0;


// synthesis translate_off
`include "LUT_accel_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //LUT_accel

