// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module filter2d_accel_xFApplyFilter2D_15_15_3_3_3_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        shift,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [23:0] p_read;
input  [23:0] p_read1;
input  [23:0] p_read2;
input  [23:0] p_read3;
input  [23:0] p_read4;
input  [23:0] p_read5;
input  [23:0] p_read6;
input  [23:0] p_read7;
input  [23:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [7:0] shift;
output  [23:0] ap_return;
input   ap_ce;

reg[23:0] ap_return;

reg   [7:0] shift_read_reg_1091;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] shift_read_reg_1091_pp0_iter1_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter2_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter3_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter4_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter5_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter6_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter7_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter8_reg;
reg   [7:0] shift_read_reg_1091_pp0_iter9_reg;
reg   [15:0] p_read_10_reg_1096;
reg   [15:0] p_read_10_reg_1096_pp0_iter1_reg;
reg   [15:0] p_read_10_reg_1096_pp0_iter2_reg;
reg   [15:0] p_read_10_reg_1096_pp0_iter3_reg;
reg   [15:0] p_read_10_reg_1096_pp0_iter4_reg;
reg   [15:0] p_read_10_reg_1096_pp0_iter5_reg;
reg   [15:0] p_read_11_reg_1101;
reg   [15:0] p_read_11_reg_1101_pp0_iter1_reg;
reg   [15:0] p_read_13_reg_1106;
reg   [15:0] p_read_13_reg_1106_pp0_iter1_reg;
reg   [15:0] p_read_13_reg_1106_pp0_iter2_reg;
reg   [15:0] p_read_14_reg_1111;
reg   [15:0] p_read_14_reg_1111_pp0_iter1_reg;
reg   [15:0] p_read_14_reg_1111_pp0_iter2_reg;
reg   [15:0] p_read_14_reg_1111_pp0_iter3_reg;
reg   [15:0] p_read_15_reg_1116;
reg   [15:0] p_read_15_reg_1116_pp0_iter1_reg;
reg   [15:0] p_read_18_reg_1121;
reg   [15:0] p_read_18_reg_1121_pp0_iter1_reg;
wire   [7:0] trunc_ln674_fu_184_p1;
reg   [7:0] trunc_ln674_reg_1126;
reg   [7:0] trunc_ln674_reg_1126_pp0_iter1_reg;
wire  signed [23:0] sext_ln69_1_fu_196_p1;
wire  signed [23:0] sext_ln69_3_fu_208_p1;
wire   [7:0] trunc_ln674_3_fu_212_p1;
reg   [7:0] trunc_ln674_3_reg_1155;
reg   [7:0] trunc_ln674_3_reg_1155_pp0_iter1_reg;
wire   [7:0] trunc_ln674_4_fu_216_p1;
reg   [7:0] trunc_ln674_4_reg_1160;
reg   [7:0] trunc_ln674_4_reg_1160_pp0_iter1_reg;
reg   [7:0] trunc_ln674_4_reg_1160_pp0_iter2_reg;
reg   [7:0] trunc_ln674_4_reg_1160_pp0_iter3_reg;
wire   [7:0] trunc_ln674_5_fu_220_p1;
reg   [7:0] trunc_ln674_5_reg_1165;
reg   [7:0] trunc_ln674_5_reg_1165_pp0_iter1_reg;
reg   [7:0] trunc_ln674_5_reg_1165_pp0_iter2_reg;
wire  signed [23:0] sext_ln69_10_fu_232_p1;
wire   [7:0] trunc_ln674_7_fu_236_p1;
reg   [7:0] trunc_ln674_7_reg_1182;
reg   [7:0] trunc_ln674_7_reg_1182_pp0_iter1_reg;
wire   [7:0] trunc_ln674_8_fu_240_p1;
reg   [7:0] trunc_ln674_8_reg_1187;
reg   [7:0] trunc_ln674_8_reg_1187_pp0_iter1_reg;
reg   [7:0] trunc_ln674_8_reg_1187_pp0_iter2_reg;
reg   [7:0] trunc_ln674_8_reg_1187_pp0_iter3_reg;
reg   [7:0] trunc_ln674_8_reg_1187_pp0_iter4_reg;
reg   [7:0] trunc_ln674_8_reg_1187_pp0_iter5_reg;
reg   [7:0] p_Result_4_1_reg_1192;
reg   [7:0] p_Result_4_1_reg_1192_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_1_reg_1207;
reg   [7:0] p_Result_4_1_1_reg_1207_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_1_1_reg_1212;
reg   [7:0] p_Result_4_1_1_1_reg_1212_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_1_1_reg_1212_pp0_iter2_reg;
reg   [7:0] p_Result_4_1_1_1_reg_1212_pp0_iter3_reg;
reg   [7:0] p_Result_4_1_1_2_reg_1217;
reg   [7:0] p_Result_4_1_1_2_reg_1217_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_1_2_reg_1217_pp0_iter2_reg;
reg   [7:0] p_Result_4_1_2_1_reg_1227;
reg   [7:0] p_Result_4_1_2_1_reg_1227_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_2_2_reg_1232;
reg   [7:0] p_Result_4_1_2_2_reg_1232_pp0_iter1_reg;
reg   [7:0] p_Result_4_1_2_2_reg_1232_pp0_iter2_reg;
reg   [7:0] p_Result_4_1_2_2_reg_1232_pp0_iter3_reg;
reg   [7:0] p_Result_4_1_2_2_reg_1232_pp0_iter4_reg;
reg   [7:0] p_Result_4_1_2_2_reg_1232_pp0_iter5_reg;
reg   [7:0] p_Result_4_2_reg_1237;
reg   [7:0] p_Result_4_2_reg_1237_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_1_reg_1252;
reg   [7:0] p_Result_4_2_1_reg_1252_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_1_1_reg_1257;
reg   [7:0] p_Result_4_2_1_1_reg_1257_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_1_1_reg_1257_pp0_iter2_reg;
reg   [7:0] p_Result_4_2_1_1_reg_1257_pp0_iter3_reg;
reg   [7:0] p_Result_4_2_1_2_reg_1262;
reg   [7:0] p_Result_4_2_1_2_reg_1262_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_1_2_reg_1262_pp0_iter2_reg;
reg   [7:0] p_Result_4_2_2_1_reg_1272;
reg   [7:0] p_Result_4_2_2_1_reg_1272_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_2_2_reg_1277;
reg   [7:0] p_Result_4_2_2_2_reg_1277_pp0_iter1_reg;
reg   [7:0] p_Result_4_2_2_2_reg_1277_pp0_iter2_reg;
reg   [7:0] p_Result_4_2_2_2_reg_1277_pp0_iter3_reg;
reg   [7:0] p_Result_4_2_2_2_reg_1277_pp0_iter4_reg;
reg   [7:0] p_Result_4_2_2_2_reg_1277_pp0_iter5_reg;
wire  signed [23:0] sext_ln69_fu_451_p1;
wire  signed [23:0] sext_ln69_4_fu_457_p1;
wire  signed [23:0] sext_ln69_11_fu_463_p1;
wire  signed [23:0] grp_fu_890_p2;
reg  signed [23:0] mul_ln69_1_reg_1348;
wire  signed [23:0] grp_fu_896_p2;
reg  signed [23:0] mul_ln69_2_reg_1353;
wire  signed [23:0] sext_ln69_9_fu_487_p1;
wire  signed [23:0] grp_fu_902_p2;
reg  signed [23:0] mul_ln69_6_reg_1370;
wire  signed [23:0] grp_fu_908_p2;
reg  signed [23:0] mul_ln69_10_reg_1375;
wire  signed [23:0] grp_fu_914_p2;
reg  signed [23:0] mul_ln69_11_reg_1380;
wire  signed [23:0] grp_fu_920_p2;
reg  signed [23:0] mul_ln69_15_reg_1390;
wire  signed [23:0] grp_fu_926_p2;
reg  signed [23:0] mul_ln69_19_reg_1395;
wire  signed [23:0] grp_fu_932_p2;
reg  signed [23:0] mul_ln69_20_reg_1400;
wire  signed [23:0] grp_fu_938_p2;
reg  signed [23:0] mul_ln69_24_reg_1410;
wire  signed [23:0] sext_ln69_7_fu_505_p1;
wire  signed [24:0] grp_fu_944_p3;
reg  signed [24:0] add_ln69_reg_1482;
wire  signed [24:0] grp_fu_952_p3;
reg  signed [24:0] add_ln69_1_reg_1487;
wire  signed [24:0] grp_fu_969_p3;
reg  signed [24:0] add_ln69_8_reg_1497;
wire  signed [24:0] grp_fu_977_p3;
reg  signed [24:0] add_ln69_9_reg_1502;
wire  signed [24:0] grp_fu_994_p3;
reg  signed [24:0] add_ln69_16_reg_1512;
wire  signed [24:0] grp_fu_1002_p3;
reg  signed [24:0] add_ln69_17_reg_1517;
wire  signed [25:0] grp_fu_1019_p3;
reg  signed [25:0] add_ln69_5_reg_1532;
reg  signed [25:0] add_ln69_5_reg_1532_pp0_iter7_reg;
wire  signed [23:0] sext_ln69_15_fu_563_p1;
wire  signed [25:0] grp_fu_1027_p3;
reg  signed [25:0] add_ln69_13_reg_1554;
reg  signed [25:0] add_ln69_13_reg_1554_pp0_iter7_reg;
wire  signed [25:0] grp_fu_1035_p3;
reg  signed [25:0] add_ln69_21_reg_1569;
reg  signed [25:0] add_ln69_21_reg_1569_pp0_iter7_reg;
wire  signed [26:0] grp_fu_1043_p3;
reg  signed [26:0] add_ln69_3_reg_1579;
wire  signed [26:0] grp_fu_1051_p3;
reg  signed [26:0] add_ln69_11_reg_1584;
wire  signed [26:0] grp_fu_1059_p3;
reg  signed [26:0] add_ln69_19_reg_1589;
wire  signed [27:0] grp_fu_1067_p3;
reg  signed [27:0] add_ln69_7_reg_1609;
wire  signed [27:0] grp_fu_1075_p3;
reg  signed [27:0] add_ln69_15_reg_1614;
wire  signed [27:0] grp_fu_1083_p3;
reg  signed [27:0] add_ln69_23_reg_1619;
wire   [31:0] ashr_ln1519_fu_646_p2;
reg   [31:0] ashr_ln1519_reg_1624;
reg   [19:0] tmp_reg_1629;
reg   [0:0] tmp_8_reg_1634;
wire   [31:0] ashr_ln1519_1_fu_673_p2;
reg   [31:0] ashr_ln1519_1_reg_1640;
reg   [19:0] tmp_9_reg_1645;
reg   [0:0] tmp_10_reg_1650;
wire   [31:0] ashr_ln1519_2_fu_700_p2;
reg   [31:0] ashr_ln1519_2_reg_1656;
reg   [19:0] tmp_11_reg_1661;
reg   [0:0] tmp_12_reg_1666;
wire    ap_block_pp0_stage0;
wire   [7:0] trunc_ln674_1_fu_188_p1;
wire   [7:0] trunc_ln674_2_fu_200_p1;
wire   [7:0] trunc_ln674_6_fu_224_p1;
wire   [7:0] p_Result_4_1_0_1_fu_254_p4;
wire   [7:0] p_Result_4_1_0_2_fu_268_p4;
wire   [7:0] p_Result_4_1_2_fu_312_p4;
wire   [7:0] p_Result_4_2_0_1_fu_356_p4;
wire   [7:0] p_Result_4_2_0_2_fu_370_p4;
wire   [7:0] p_Result_4_2_2_fu_414_p4;
wire  signed [24:0] grp_fu_960_p3;
wire  signed [24:0] grp_fu_985_p3;
wire  signed [24:0] grp_fu_1010_p3;
wire  signed [25:0] sext_ln69_6_fu_547_p1;
wire  signed [25:0] sext_ln674_1_fu_544_p1;
wire  signed [25:0] add_ln69_2_fu_550_p2;
wire  signed [25:0] sext_ln69_19_fu_569_p1;
wire  signed [25:0] sext_ln674_5_fu_566_p1;
wire  signed [25:0] add_ln69_10_fu_572_p2;
wire  signed [25:0] sext_ln69_27_fu_588_p1;
wire  signed [25:0] sext_ln674_9_fu_585_p1;
wire  signed [25:0] add_ln69_18_fu_591_p2;
wire  signed [26:0] sext_ln69_14_fu_604_p1;
(* use_dsp48 = "no" *) wire  signed [26:0] add_ln69_6_fu_607_p2;
wire  signed [26:0] sext_ln69_23_fu_616_p1;
(* use_dsp48 = "no" *) wire  signed [26:0] add_ln69_14_fu_619_p2;
wire  signed [26:0] sext_ln69_31_fu_628_p1;
(* use_dsp48 = "no" *) wire  signed [26:0] add_ln69_22_fu_631_p2;
wire  signed [31:0] sext_ln1519_fu_643_p1;
wire   [31:0] conv_i92_fu_640_p1;
wire  signed [31:0] sext_ln1519_1_fu_670_p1;
wire  signed [31:0] sext_ln1519_2_fu_697_p1;
wire   [0:0] icmp_ln886_fu_724_p2;
wire   [0:0] xor_ln886_fu_732_p2;
wire   [0:0] xor_ln878_fu_743_p2;
wire   [0:0] or_ln878_3_fu_748_p2;
wire   [0:0] and_ln878_fu_738_p2;
wire   [0:0] or_ln878_fu_762_p2;
wire   [7:0] select_ln878_fu_754_p3;
wire   [7:0] trunc_ln215_fu_729_p1;
wire   [0:0] icmp_ln886_1_fu_776_p2;
wire   [0:0] xor_ln886_1_fu_784_p2;
wire   [0:0] xor_ln878_1_fu_795_p2;
wire   [0:0] or_ln878_4_fu_800_p2;
wire   [0:0] and_ln878_1_fu_790_p2;
wire   [0:0] or_ln878_1_fu_814_p2;
wire   [7:0] select_ln878_2_fu_806_p3;
wire   [7:0] trunc_ln215_1_fu_781_p1;
wire   [0:0] icmp_ln886_2_fu_828_p2;
wire   [0:0] xor_ln886_2_fu_836_p2;
wire   [0:0] xor_ln878_2_fu_847_p2;
wire   [0:0] or_ln878_5_fu_852_p2;
wire   [0:0] and_ln878_2_fu_842_p2;
wire   [0:0] or_ln878_2_fu_866_p2;
wire   [7:0] select_ln878_4_fu_858_p3;
wire   [7:0] trunc_ln215_2_fu_833_p1;
wire   [7:0] select_ln878_5_fu_872_p3;
wire   [7:0] select_ln878_3_fu_820_p3;
wire   [7:0] select_ln878_1_fu_768_p3;
wire  signed [15:0] grp_fu_890_p0;
wire   [7:0] grp_fu_890_p1;
wire  signed [15:0] grp_fu_896_p0;
wire   [7:0] grp_fu_896_p1;
wire  signed [15:0] grp_fu_902_p0;
wire   [7:0] grp_fu_902_p1;
wire  signed [15:0] grp_fu_908_p0;
wire   [7:0] grp_fu_908_p1;
wire  signed [15:0] grp_fu_914_p0;
wire   [7:0] grp_fu_914_p1;
wire  signed [15:0] grp_fu_920_p0;
wire   [7:0] grp_fu_920_p1;
wire  signed [15:0] grp_fu_926_p0;
wire   [7:0] grp_fu_926_p1;
wire  signed [15:0] grp_fu_932_p0;
wire   [7:0] grp_fu_932_p1;
wire  signed [15:0] grp_fu_938_p0;
wire   [7:0] grp_fu_938_p1;
wire  signed [15:0] grp_fu_944_p0;
wire   [7:0] grp_fu_944_p1;
wire  signed [15:0] grp_fu_952_p0;
wire   [7:0] grp_fu_952_p1;
wire  signed [15:0] grp_fu_960_p0;
wire   [7:0] grp_fu_960_p1;
wire  signed [15:0] grp_fu_969_p0;
wire   [7:0] grp_fu_969_p1;
wire  signed [15:0] grp_fu_977_p0;
wire   [7:0] grp_fu_977_p1;
wire  signed [15:0] grp_fu_985_p0;
wire   [7:0] grp_fu_985_p1;
wire  signed [15:0] grp_fu_994_p0;
wire   [7:0] grp_fu_994_p1;
wire  signed [15:0] grp_fu_1002_p0;
wire   [7:0] grp_fu_1002_p1;
wire  signed [15:0] grp_fu_1010_p0;
wire   [7:0] grp_fu_1010_p1;
wire  signed [15:0] grp_fu_1019_p0;
wire   [7:0] grp_fu_1019_p1;
wire  signed [15:0] grp_fu_1027_p0;
wire   [7:0] grp_fu_1027_p1;
wire  signed [15:0] grp_fu_1035_p0;
wire   [7:0] grp_fu_1035_p1;
wire  signed [15:0] grp_fu_1043_p0;
wire   [7:0] grp_fu_1043_p1;
wire  signed [15:0] grp_fu_1051_p0;
wire   [7:0] grp_fu_1051_p1;
wire  signed [15:0] grp_fu_1059_p0;
wire   [7:0] grp_fu_1059_p1;
wire  signed [15:0] grp_fu_1067_p0;
wire   [7:0] grp_fu_1067_p1;
wire  signed [15:0] grp_fu_1075_p0;
wire   [7:0] grp_fu_1075_p1;
wire  signed [15:0] grp_fu_1083_p0;
wire   [7:0] grp_fu_1083_p1;
wire   [23:0] out_1_2_fu_880_p4;
reg    grp_fu_890_ce;
reg    grp_fu_896_ce;
reg    grp_fu_902_ce;
reg    grp_fu_908_ce;
reg    grp_fu_914_ce;
reg    grp_fu_920_ce;
reg    grp_fu_926_ce;
reg    grp_fu_932_ce;
reg    grp_fu_938_ce;
reg    grp_fu_944_ce;
reg    grp_fu_952_ce;
reg    grp_fu_960_ce;
reg    grp_fu_969_ce;
reg    grp_fu_977_ce;
reg    grp_fu_985_ce;
reg    grp_fu_994_ce;
reg    grp_fu_1002_ce;
reg    grp_fu_1010_ce;
reg    grp_fu_1019_ce;
reg    grp_fu_1027_ce;
reg    grp_fu_1035_ce;
reg    grp_fu_1043_ce;
reg    grp_fu_1051_ce;
reg    grp_fu_1059_ce;
reg    grp_fu_1067_ce;
reg    grp_fu_1075_ce;
reg    grp_fu_1083_ce;
reg    ap_ce_reg;
reg   [23:0] p_read_int_reg;
reg   [23:0] p_read1_int_reg;
reg   [23:0] p_read2_int_reg;
reg   [23:0] p_read3_int_reg;
reg   [23:0] p_read4_int_reg;
reg   [23:0] p_read5_int_reg;
reg   [23:0] p_read6_int_reg;
reg   [23:0] p_read7_int_reg;
reg   [23:0] p_read8_int_reg;
reg   [15:0] p_read9_int_reg;
reg   [15:0] p_read10_int_reg;
reg   [15:0] p_read11_int_reg;
reg   [15:0] p_read12_int_reg;
reg   [15:0] p_read13_int_reg;
reg   [15:0] p_read14_int_reg;
reg   [15:0] p_read15_int_reg;
reg   [15:0] p_read16_int_reg;
reg   [15:0] p_read17_int_reg;
reg   [7:0] shift_int_reg;
reg   [23:0] ap_return_int_reg;
wire   [23:0] grp_fu_1002_p10;
wire   [23:0] grp_fu_1010_p10;
wire   [23:0] grp_fu_1019_p10;
wire   [23:0] grp_fu_1027_p10;
wire   [23:0] grp_fu_1035_p10;
wire   [23:0] grp_fu_1043_p10;
wire   [23:0] grp_fu_1051_p10;
wire   [23:0] grp_fu_1059_p10;
wire   [23:0] grp_fu_1067_p10;
wire   [23:0] grp_fu_1075_p10;
wire   [23:0] grp_fu_1083_p10;
wire   [23:0] grp_fu_890_p10;
wire   [23:0] grp_fu_896_p10;
wire   [23:0] grp_fu_902_p10;
wire   [23:0] grp_fu_908_p10;
wire   [23:0] grp_fu_914_p10;
wire   [23:0] grp_fu_920_p10;
wire   [23:0] grp_fu_926_p10;
wire   [23:0] grp_fu_932_p10;
wire   [23:0] grp_fu_938_p10;
wire   [23:0] grp_fu_944_p10;
wire   [23:0] grp_fu_952_p10;
wire   [23:0] grp_fu_960_p10;
wire   [23:0] grp_fu_969_p10;
wire   [23:0] grp_fu_977_p10;
wire   [23:0] grp_fu_985_p10;
wire   [23:0] grp_fu_994_p10;

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_890_p0),
    .din1(grp_fu_890_p1),
    .ce(grp_fu_890_ce),
    .dout(grp_fu_890_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_896_p0),
    .din1(grp_fu_896_p1),
    .ce(grp_fu_896_ce),
    .dout(grp_fu_896_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_902_p0),
    .din1(grp_fu_902_p1),
    .ce(grp_fu_902_ce),
    .dout(grp_fu_902_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_908_p0),
    .din1(grp_fu_908_p1),
    .ce(grp_fu_908_ce),
    .dout(grp_fu_908_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_914_p0),
    .din1(grp_fu_914_p1),
    .ce(grp_fu_914_ce),
    .dout(grp_fu_914_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_920_p0),
    .din1(grp_fu_920_p1),
    .ce(grp_fu_920_ce),
    .dout(grp_fu_920_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_926_p0),
    .din1(grp_fu_926_p1),
    .ce(grp_fu_926_ce),
    .dout(grp_fu_926_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_932_p0),
    .din1(grp_fu_932_p1),
    .ce(grp_fu_932_ce),
    .dout(grp_fu_932_p2)
);

filter2d_accel_mul_mul_16s_8ns_24_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_mul_16s_8ns_24_4_0_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_938_p0),
    .din1(grp_fu_938_p1),
    .ce(grp_fu_938_ce),
    .dout(grp_fu_938_p2)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_944_p0),
    .din1(grp_fu_944_p1),
    .din2(mul_ln69_1_reg_1348),
    .ce(grp_fu_944_ce),
    .dout(grp_fu_944_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_952_p0),
    .din1(grp_fu_952_p1),
    .din2(mul_ln69_2_reg_1353),
    .ce(grp_fu_952_ce),
    .dout(grp_fu_952_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_960_p0),
    .din1(grp_fu_960_p1),
    .din2(mul_ln69_6_reg_1370),
    .ce(grp_fu_960_ce),
    .dout(grp_fu_960_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_969_p0),
    .din1(grp_fu_969_p1),
    .din2(mul_ln69_10_reg_1375),
    .ce(grp_fu_969_ce),
    .dout(grp_fu_969_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_977_p0),
    .din1(grp_fu_977_p1),
    .din2(mul_ln69_11_reg_1380),
    .ce(grp_fu_977_ce),
    .dout(grp_fu_977_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_985_p0),
    .din1(grp_fu_985_p1),
    .din2(mul_ln69_15_reg_1390),
    .ce(grp_fu_985_ce),
    .dout(grp_fu_985_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_994_p0),
    .din1(grp_fu_994_p1),
    .din2(mul_ln69_19_reg_1395),
    .ce(grp_fu_994_ce),
    .dout(grp_fu_994_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1002_p0),
    .din1(grp_fu_1002_p1),
    .din2(mul_ln69_20_reg_1400),
    .ce(grp_fu_1002_ce),
    .dout(grp_fu_1002_p3)
);

filter2d_accel_mac_muladd_16s_8ns_24s_25_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_16s_8ns_24s_25_4_0_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1010_p0),
    .din1(grp_fu_1010_p1),
    .din2(mul_ln69_24_reg_1410),
    .ce(grp_fu_1010_ce),
    .dout(grp_fu_1010_p3)
);

filter2d_accel_mac_muladd_16s_8ns_25s_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_8ns_25s_26_4_0_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1019_p0),
    .din1(grp_fu_1019_p1),
    .din2(grp_fu_960_p3),
    .ce(grp_fu_1019_ce),
    .dout(grp_fu_1019_p3)
);

filter2d_accel_mac_muladd_16s_8ns_25s_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_8ns_25s_26_4_0_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1027_p0),
    .din1(grp_fu_1027_p1),
    .din2(grp_fu_985_p3),
    .ce(grp_fu_1027_ce),
    .dout(grp_fu_1027_p3)
);

filter2d_accel_mac_muladd_16s_8ns_25s_26_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_16s_8ns_25s_26_4_0_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1035_p0),
    .din1(grp_fu_1035_p1),
    .din2(grp_fu_1010_p3),
    .ce(grp_fu_1035_ce),
    .dout(grp_fu_1035_p3)
);

filter2d_accel_mac_muladd_16s_8ns_26s_27_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_8ns_26s_27_4_0_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1043_p0),
    .din1(grp_fu_1043_p1),
    .din2(add_ln69_2_fu_550_p2),
    .ce(grp_fu_1043_ce),
    .dout(grp_fu_1043_p3)
);

filter2d_accel_mac_muladd_16s_8ns_26s_27_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_8ns_26s_27_4_0_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1051_p0),
    .din1(grp_fu_1051_p1),
    .din2(add_ln69_10_fu_572_p2),
    .ce(grp_fu_1051_ce),
    .dout(grp_fu_1051_p3)
);

filter2d_accel_mac_muladd_16s_8ns_26s_27_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_8ns_26s_27_4_0_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1059_p0),
    .din1(grp_fu_1059_p1),
    .din2(add_ln69_18_fu_591_p2),
    .ce(grp_fu_1059_ce),
    .dout(grp_fu_1059_p3)
);

filter2d_accel_mac_muladd_16s_8ns_27s_28_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_8ns_27s_28_4_0_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1067_p0),
    .din1(grp_fu_1067_p1),
    .din2(add_ln69_6_fu_607_p2),
    .ce(grp_fu_1067_ce),
    .dout(grp_fu_1067_p3)
);

filter2d_accel_mac_muladd_16s_8ns_27s_28_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_8ns_27s_28_4_0_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1075_p0),
    .din1(grp_fu_1075_p1),
    .din2(add_ln69_14_fu_619_p2),
    .ce(grp_fu_1075_ce),
    .dout(grp_fu_1075_p3)
);

filter2d_accel_mac_muladd_16s_8ns_27s_28_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 28 ))
mac_muladd_16s_8ns_27s_28_4_0_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1083_p0),
    .din1(grp_fu_1083_p1),
    .din2(add_ln69_22_fu_631_p2),
    .ce(grp_fu_1083_ce),
    .dout(grp_fu_1083_p3)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln69_11_reg_1584 <= grp_fu_1051_p3;
        add_ln69_13_reg_1554 <= grp_fu_1027_p3;
        add_ln69_13_reg_1554_pp0_iter7_reg <= add_ln69_13_reg_1554;
        add_ln69_15_reg_1614 <= grp_fu_1075_p3;
        add_ln69_16_reg_1512 <= grp_fu_994_p3;
        add_ln69_17_reg_1517 <= grp_fu_1002_p3;
        add_ln69_19_reg_1589 <= grp_fu_1059_p3;
        add_ln69_1_reg_1487 <= grp_fu_952_p3;
        add_ln69_21_reg_1569 <= grp_fu_1035_p3;
        add_ln69_21_reg_1569_pp0_iter7_reg <= add_ln69_21_reg_1569;
        add_ln69_23_reg_1619 <= grp_fu_1083_p3;
        add_ln69_3_reg_1579 <= grp_fu_1043_p3;
        add_ln69_5_reg_1532 <= grp_fu_1019_p3;
        add_ln69_5_reg_1532_pp0_iter7_reg <= add_ln69_5_reg_1532;
        add_ln69_7_reg_1609 <= grp_fu_1067_p3;
        add_ln69_8_reg_1497 <= grp_fu_969_p3;
        add_ln69_9_reg_1502 <= grp_fu_977_p3;
        add_ln69_reg_1482 <= grp_fu_944_p3;
        ashr_ln1519_1_reg_1640 <= ashr_ln1519_1_fu_673_p2;
        ashr_ln1519_2_reg_1656 <= ashr_ln1519_2_fu_700_p2;
        ashr_ln1519_reg_1624 <= ashr_ln1519_fu_646_p2;
        mul_ln69_10_reg_1375 <= grp_fu_908_p2;
        mul_ln69_11_reg_1380 <= grp_fu_914_p2;
        mul_ln69_15_reg_1390 <= grp_fu_920_p2;
        mul_ln69_19_reg_1395 <= grp_fu_926_p2;
        mul_ln69_1_reg_1348 <= grp_fu_890_p2;
        mul_ln69_20_reg_1400 <= grp_fu_932_p2;
        mul_ln69_24_reg_1410 <= grp_fu_938_p2;
        mul_ln69_2_reg_1353 <= grp_fu_896_p2;
        mul_ln69_6_reg_1370 <= grp_fu_902_p2;
        p_Result_4_1_1_1_reg_1212 <= {{p_read4_int_reg[15:8]}};
        p_Result_4_1_1_1_reg_1212_pp0_iter1_reg <= p_Result_4_1_1_1_reg_1212;
        p_Result_4_1_1_1_reg_1212_pp0_iter2_reg <= p_Result_4_1_1_1_reg_1212_pp0_iter1_reg;
        p_Result_4_1_1_1_reg_1212_pp0_iter3_reg <= p_Result_4_1_1_1_reg_1212_pp0_iter2_reg;
        p_Result_4_1_1_2_reg_1217 <= {{p_read3_int_reg[15:8]}};
        p_Result_4_1_1_2_reg_1217_pp0_iter1_reg <= p_Result_4_1_1_2_reg_1217;
        p_Result_4_1_1_2_reg_1217_pp0_iter2_reg <= p_Result_4_1_1_2_reg_1217_pp0_iter1_reg;
        p_Result_4_1_1_reg_1207 <= {{p_read5_int_reg[15:8]}};
        p_Result_4_1_1_reg_1207_pp0_iter1_reg <= p_Result_4_1_1_reg_1207;
        p_Result_4_1_2_1_reg_1227 <= {{p_read1_int_reg[15:8]}};
        p_Result_4_1_2_1_reg_1227_pp0_iter1_reg <= p_Result_4_1_2_1_reg_1227;
        p_Result_4_1_2_2_reg_1232 <= {{p_read_int_reg[15:8]}};
        p_Result_4_1_2_2_reg_1232_pp0_iter1_reg <= p_Result_4_1_2_2_reg_1232;
        p_Result_4_1_2_2_reg_1232_pp0_iter2_reg <= p_Result_4_1_2_2_reg_1232_pp0_iter1_reg;
        p_Result_4_1_2_2_reg_1232_pp0_iter3_reg <= p_Result_4_1_2_2_reg_1232_pp0_iter2_reg;
        p_Result_4_1_2_2_reg_1232_pp0_iter4_reg <= p_Result_4_1_2_2_reg_1232_pp0_iter3_reg;
        p_Result_4_1_2_2_reg_1232_pp0_iter5_reg <= p_Result_4_1_2_2_reg_1232_pp0_iter4_reg;
        p_Result_4_1_reg_1192 <= {{p_read8_int_reg[15:8]}};
        p_Result_4_1_reg_1192_pp0_iter1_reg <= p_Result_4_1_reg_1192;
        p_Result_4_2_1_1_reg_1257 <= {{p_read4_int_reg[23:16]}};
        p_Result_4_2_1_1_reg_1257_pp0_iter1_reg <= p_Result_4_2_1_1_reg_1257;
        p_Result_4_2_1_1_reg_1257_pp0_iter2_reg <= p_Result_4_2_1_1_reg_1257_pp0_iter1_reg;
        p_Result_4_2_1_1_reg_1257_pp0_iter3_reg <= p_Result_4_2_1_1_reg_1257_pp0_iter2_reg;
        p_Result_4_2_1_2_reg_1262 <= {{p_read3_int_reg[23:16]}};
        p_Result_4_2_1_2_reg_1262_pp0_iter1_reg <= p_Result_4_2_1_2_reg_1262;
        p_Result_4_2_1_2_reg_1262_pp0_iter2_reg <= p_Result_4_2_1_2_reg_1262_pp0_iter1_reg;
        p_Result_4_2_1_reg_1252 <= {{p_read5_int_reg[23:16]}};
        p_Result_4_2_1_reg_1252_pp0_iter1_reg <= p_Result_4_2_1_reg_1252;
        p_Result_4_2_2_1_reg_1272 <= {{p_read1_int_reg[23:16]}};
        p_Result_4_2_2_1_reg_1272_pp0_iter1_reg <= p_Result_4_2_2_1_reg_1272;
        p_Result_4_2_2_2_reg_1277 <= {{p_read_int_reg[23:16]}};
        p_Result_4_2_2_2_reg_1277_pp0_iter1_reg <= p_Result_4_2_2_2_reg_1277;
        p_Result_4_2_2_2_reg_1277_pp0_iter2_reg <= p_Result_4_2_2_2_reg_1277_pp0_iter1_reg;
        p_Result_4_2_2_2_reg_1277_pp0_iter3_reg <= p_Result_4_2_2_2_reg_1277_pp0_iter2_reg;
        p_Result_4_2_2_2_reg_1277_pp0_iter4_reg <= p_Result_4_2_2_2_reg_1277_pp0_iter3_reg;
        p_Result_4_2_2_2_reg_1277_pp0_iter5_reg <= p_Result_4_2_2_2_reg_1277_pp0_iter4_reg;
        p_Result_4_2_reg_1237 <= {{p_read8_int_reg[23:16]}};
        p_Result_4_2_reg_1237_pp0_iter1_reg <= p_Result_4_2_reg_1237;
        p_read_10_reg_1096 <= p_read17_int_reg;
        p_read_10_reg_1096_pp0_iter1_reg <= p_read_10_reg_1096;
        p_read_10_reg_1096_pp0_iter2_reg <= p_read_10_reg_1096_pp0_iter1_reg;
        p_read_10_reg_1096_pp0_iter3_reg <= p_read_10_reg_1096_pp0_iter2_reg;
        p_read_10_reg_1096_pp0_iter4_reg <= p_read_10_reg_1096_pp0_iter3_reg;
        p_read_10_reg_1096_pp0_iter5_reg <= p_read_10_reg_1096_pp0_iter4_reg;
        p_read_11_reg_1101 <= p_read16_int_reg;
        p_read_11_reg_1101_pp0_iter1_reg <= p_read_11_reg_1101;
        p_read_13_reg_1106 <= p_read14_int_reg;
        p_read_13_reg_1106_pp0_iter1_reg <= p_read_13_reg_1106;
        p_read_13_reg_1106_pp0_iter2_reg <= p_read_13_reg_1106_pp0_iter1_reg;
        p_read_14_reg_1111 <= p_read13_int_reg;
        p_read_14_reg_1111_pp0_iter1_reg <= p_read_14_reg_1111;
        p_read_14_reg_1111_pp0_iter2_reg <= p_read_14_reg_1111_pp0_iter1_reg;
        p_read_14_reg_1111_pp0_iter3_reg <= p_read_14_reg_1111_pp0_iter2_reg;
        p_read_15_reg_1116 <= p_read12_int_reg;
        p_read_15_reg_1116_pp0_iter1_reg <= p_read_15_reg_1116;
        p_read_18_reg_1121 <= p_read9_int_reg;
        p_read_18_reg_1121_pp0_iter1_reg <= p_read_18_reg_1121;
        shift_read_reg_1091 <= shift_int_reg;
        shift_read_reg_1091_pp0_iter1_reg <= shift_read_reg_1091;
        shift_read_reg_1091_pp0_iter2_reg <= shift_read_reg_1091_pp0_iter1_reg;
        shift_read_reg_1091_pp0_iter3_reg <= shift_read_reg_1091_pp0_iter2_reg;
        shift_read_reg_1091_pp0_iter4_reg <= shift_read_reg_1091_pp0_iter3_reg;
        shift_read_reg_1091_pp0_iter5_reg <= shift_read_reg_1091_pp0_iter4_reg;
        shift_read_reg_1091_pp0_iter6_reg <= shift_read_reg_1091_pp0_iter5_reg;
        shift_read_reg_1091_pp0_iter7_reg <= shift_read_reg_1091_pp0_iter6_reg;
        shift_read_reg_1091_pp0_iter8_reg <= shift_read_reg_1091_pp0_iter7_reg;
        shift_read_reg_1091_pp0_iter9_reg <= shift_read_reg_1091_pp0_iter8_reg;
        tmp_10_reg_1650 <= ashr_ln1519_1_fu_673_p2[32'd27];
        tmp_11_reg_1661 <= {{ashr_ln1519_2_fu_700_p2[27:8]}};
        tmp_12_reg_1666 <= ashr_ln1519_2_fu_700_p2[32'd27];
        tmp_8_reg_1634 <= ashr_ln1519_fu_646_p2[32'd27];
        tmp_9_reg_1645 <= {{ashr_ln1519_1_fu_673_p2[27:8]}};
        tmp_reg_1629 <= {{ashr_ln1519_fu_646_p2[27:8]}};
        trunc_ln674_3_reg_1155 <= trunc_ln674_3_fu_212_p1;
        trunc_ln674_3_reg_1155_pp0_iter1_reg <= trunc_ln674_3_reg_1155;
        trunc_ln674_4_reg_1160 <= trunc_ln674_4_fu_216_p1;
        trunc_ln674_4_reg_1160_pp0_iter1_reg <= trunc_ln674_4_reg_1160;
        trunc_ln674_4_reg_1160_pp0_iter2_reg <= trunc_ln674_4_reg_1160_pp0_iter1_reg;
        trunc_ln674_4_reg_1160_pp0_iter3_reg <= trunc_ln674_4_reg_1160_pp0_iter2_reg;
        trunc_ln674_5_reg_1165 <= trunc_ln674_5_fu_220_p1;
        trunc_ln674_5_reg_1165_pp0_iter1_reg <= trunc_ln674_5_reg_1165;
        trunc_ln674_5_reg_1165_pp0_iter2_reg <= trunc_ln674_5_reg_1165_pp0_iter1_reg;
        trunc_ln674_7_reg_1182 <= trunc_ln674_7_fu_236_p1;
        trunc_ln674_7_reg_1182_pp0_iter1_reg <= trunc_ln674_7_reg_1182;
        trunc_ln674_8_reg_1187 <= trunc_ln674_8_fu_240_p1;
        trunc_ln674_8_reg_1187_pp0_iter1_reg <= trunc_ln674_8_reg_1187;
        trunc_ln674_8_reg_1187_pp0_iter2_reg <= trunc_ln674_8_reg_1187_pp0_iter1_reg;
        trunc_ln674_8_reg_1187_pp0_iter3_reg <= trunc_ln674_8_reg_1187_pp0_iter2_reg;
        trunc_ln674_8_reg_1187_pp0_iter4_reg <= trunc_ln674_8_reg_1187_pp0_iter3_reg;
        trunc_ln674_8_reg_1187_pp0_iter5_reg <= trunc_ln674_8_reg_1187_pp0_iter4_reg;
        trunc_ln674_reg_1126 <= trunc_ln674_fu_184_p1;
        trunc_ln674_reg_1126_pp0_iter1_reg <= trunc_ln674_reg_1126;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= out_1_2_fu_880_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read12_int_reg <= p_read12;
        p_read13_int_reg <= p_read13;
        p_read14_int_reg <= p_read14;
        p_read15_int_reg <= p_read15;
        p_read16_int_reg <= p_read16;
        p_read17_int_reg <= p_read17;
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
        p_read_int_reg <= p_read;
        shift_int_reg <= shift;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = out_1_2_fu_880_p4;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1002_ce = 1'b1;
    end else begin
        grp_fu_1002_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1010_ce = 1'b1;
    end else begin
        grp_fu_1010_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1019_ce = 1'b1;
    end else begin
        grp_fu_1019_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1027_ce = 1'b1;
    end else begin
        grp_fu_1027_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1035_ce = 1'b1;
    end else begin
        grp_fu_1035_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1043_ce = 1'b1;
    end else begin
        grp_fu_1043_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1051_ce = 1'b1;
    end else begin
        grp_fu_1051_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1059_ce = 1'b1;
    end else begin
        grp_fu_1059_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1067_ce = 1'b1;
    end else begin
        grp_fu_1067_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1075_ce = 1'b1;
    end else begin
        grp_fu_1075_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_1083_ce = 1'b1;
    end else begin
        grp_fu_1083_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_890_ce = 1'b1;
    end else begin
        grp_fu_890_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_896_ce = 1'b1;
    end else begin
        grp_fu_896_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_902_ce = 1'b1;
    end else begin
        grp_fu_902_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_908_ce = 1'b1;
    end else begin
        grp_fu_908_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_914_ce = 1'b1;
    end else begin
        grp_fu_914_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_920_ce = 1'b1;
    end else begin
        grp_fu_920_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_926_ce = 1'b1;
    end else begin
        grp_fu_926_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_932_ce = 1'b1;
    end else begin
        grp_fu_932_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_938_ce = 1'b1;
    end else begin
        grp_fu_938_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_944_ce = 1'b1;
    end else begin
        grp_fu_944_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_952_ce = 1'b1;
    end else begin
        grp_fu_952_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_960_ce = 1'b1;
    end else begin
        grp_fu_960_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_969_ce = 1'b1;
    end else begin
        grp_fu_969_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_977_ce = 1'b1;
    end else begin
        grp_fu_977_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_985_ce = 1'b1;
    end else begin
        grp_fu_985_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_994_ce = 1'b1;
    end else begin
        grp_fu_994_ce = 1'b0;
    end
end

assign add_ln69_10_fu_572_p2 = ($signed(sext_ln69_19_fu_569_p1) + $signed(sext_ln674_5_fu_566_p1));

assign add_ln69_14_fu_619_p2 = ($signed(sext_ln69_23_fu_616_p1) + $signed(add_ln69_11_reg_1584));

assign add_ln69_18_fu_591_p2 = ($signed(sext_ln69_27_fu_588_p1) + $signed(sext_ln674_9_fu_585_p1));

assign add_ln69_22_fu_631_p2 = ($signed(sext_ln69_31_fu_628_p1) + $signed(add_ln69_19_reg_1589));

assign add_ln69_2_fu_550_p2 = ($signed(sext_ln69_6_fu_547_p1) + $signed(sext_ln674_1_fu_544_p1));

assign add_ln69_6_fu_607_p2 = ($signed(sext_ln69_14_fu_604_p1) + $signed(add_ln69_3_reg_1579));

assign and_ln878_1_fu_790_p2 = (xor_ln886_1_fu_784_p2 & tmp_10_reg_1650);

assign and_ln878_2_fu_842_p2 = (xor_ln886_2_fu_836_p2 & tmp_12_reg_1666);

assign and_ln878_fu_738_p2 = (xor_ln886_fu_732_p2 & tmp_8_reg_1634);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ashr_ln1519_1_fu_673_p2 = $signed(sext_ln1519_1_fu_670_p1) >>> conv_i92_fu_640_p1;

assign ashr_ln1519_2_fu_700_p2 = $signed(sext_ln1519_2_fu_697_p1) >>> conv_i92_fu_640_p1;

assign ashr_ln1519_fu_646_p2 = $signed(sext_ln1519_fu_643_p1) >>> conv_i92_fu_640_p1;

assign conv_i92_fu_640_p1 = shift_read_reg_1091_pp0_iter9_reg;

assign grp_fu_1002_p0 = sext_ln69_4_fu_457_p1;

assign grp_fu_1002_p1 = grp_fu_1002_p10;

assign grp_fu_1002_p10 = p_Result_4_2_1_reg_1252_pp0_iter1_reg;

assign grp_fu_1010_p0 = sext_ln69_11_fu_463_p1;

assign grp_fu_1010_p1 = grp_fu_1010_p10;

assign grp_fu_1010_p10 = p_Result_4_2_2_1_reg_1272_pp0_iter1_reg;

assign grp_fu_1019_p0 = sext_ln69_9_fu_487_p1;

assign grp_fu_1019_p1 = grp_fu_1019_p10;

assign grp_fu_1019_p10 = trunc_ln674_5_reg_1165_pp0_iter2_reg;

assign grp_fu_1027_p0 = sext_ln69_9_fu_487_p1;

assign grp_fu_1027_p1 = grp_fu_1027_p10;

assign grp_fu_1027_p10 = p_Result_4_1_1_2_reg_1217_pp0_iter2_reg;

assign grp_fu_1035_p0 = sext_ln69_9_fu_487_p1;

assign grp_fu_1035_p1 = grp_fu_1035_p10;

assign grp_fu_1035_p10 = p_Result_4_2_1_2_reg_1262_pp0_iter2_reg;

assign grp_fu_1043_p0 = sext_ln69_7_fu_505_p1;

assign grp_fu_1043_p1 = grp_fu_1043_p10;

assign grp_fu_1043_p10 = trunc_ln674_4_reg_1160_pp0_iter3_reg;

assign grp_fu_1051_p0 = sext_ln69_7_fu_505_p1;

assign grp_fu_1051_p1 = grp_fu_1051_p10;

assign grp_fu_1051_p10 = p_Result_4_1_1_1_reg_1212_pp0_iter3_reg;

assign grp_fu_1059_p0 = sext_ln69_7_fu_505_p1;

assign grp_fu_1059_p1 = grp_fu_1059_p10;

assign grp_fu_1059_p10 = p_Result_4_2_1_1_reg_1257_pp0_iter3_reg;

assign grp_fu_1067_p0 = sext_ln69_15_fu_563_p1;

assign grp_fu_1067_p1 = grp_fu_1067_p10;

assign grp_fu_1067_p10 = trunc_ln674_8_reg_1187_pp0_iter5_reg;

assign grp_fu_1075_p0 = sext_ln69_15_fu_563_p1;

assign grp_fu_1075_p1 = grp_fu_1075_p10;

assign grp_fu_1075_p10 = p_Result_4_1_2_2_reg_1232_pp0_iter5_reg;

assign grp_fu_1083_p0 = sext_ln69_15_fu_563_p1;

assign grp_fu_1083_p1 = grp_fu_1083_p10;

assign grp_fu_1083_p10 = p_Result_4_2_2_2_reg_1277_pp0_iter5_reg;

assign grp_fu_890_p0 = sext_ln69_1_fu_196_p1;

assign grp_fu_890_p1 = grp_fu_890_p10;

assign grp_fu_890_p10 = trunc_ln674_1_fu_188_p1;

assign grp_fu_896_p0 = sext_ln69_3_fu_208_p1;

assign grp_fu_896_p1 = grp_fu_896_p10;

assign grp_fu_896_p10 = trunc_ln674_2_fu_200_p1;

assign grp_fu_902_p0 = sext_ln69_10_fu_232_p1;

assign grp_fu_902_p1 = grp_fu_902_p10;

assign grp_fu_902_p10 = trunc_ln674_6_fu_224_p1;

assign grp_fu_908_p0 = sext_ln69_1_fu_196_p1;

assign grp_fu_908_p1 = grp_fu_908_p10;

assign grp_fu_908_p10 = p_Result_4_1_0_1_fu_254_p4;

assign grp_fu_914_p0 = sext_ln69_3_fu_208_p1;

assign grp_fu_914_p1 = grp_fu_914_p10;

assign grp_fu_914_p10 = p_Result_4_1_0_2_fu_268_p4;

assign grp_fu_920_p0 = sext_ln69_10_fu_232_p1;

assign grp_fu_920_p1 = grp_fu_920_p10;

assign grp_fu_920_p10 = p_Result_4_1_2_fu_312_p4;

assign grp_fu_926_p0 = sext_ln69_1_fu_196_p1;

assign grp_fu_926_p1 = grp_fu_926_p10;

assign grp_fu_926_p10 = p_Result_4_2_0_1_fu_356_p4;

assign grp_fu_932_p0 = sext_ln69_3_fu_208_p1;

assign grp_fu_932_p1 = grp_fu_932_p10;

assign grp_fu_932_p10 = p_Result_4_2_0_2_fu_370_p4;

assign grp_fu_938_p0 = sext_ln69_10_fu_232_p1;

assign grp_fu_938_p1 = grp_fu_938_p10;

assign grp_fu_938_p10 = p_Result_4_2_2_fu_414_p4;

assign grp_fu_944_p0 = sext_ln69_fu_451_p1;

assign grp_fu_944_p1 = grp_fu_944_p10;

assign grp_fu_944_p10 = trunc_ln674_reg_1126_pp0_iter1_reg;

assign grp_fu_952_p0 = sext_ln69_4_fu_457_p1;

assign grp_fu_952_p1 = grp_fu_952_p10;

assign grp_fu_952_p10 = trunc_ln674_3_reg_1155_pp0_iter1_reg;

assign grp_fu_960_p0 = sext_ln69_11_fu_463_p1;

assign grp_fu_960_p1 = grp_fu_960_p10;

assign grp_fu_960_p10 = trunc_ln674_7_reg_1182_pp0_iter1_reg;

assign grp_fu_969_p0 = sext_ln69_fu_451_p1;

assign grp_fu_969_p1 = grp_fu_969_p10;

assign grp_fu_969_p10 = p_Result_4_1_reg_1192_pp0_iter1_reg;

assign grp_fu_977_p0 = sext_ln69_4_fu_457_p1;

assign grp_fu_977_p1 = grp_fu_977_p10;

assign grp_fu_977_p10 = p_Result_4_1_1_reg_1207_pp0_iter1_reg;

assign grp_fu_985_p0 = sext_ln69_11_fu_463_p1;

assign grp_fu_985_p1 = grp_fu_985_p10;

assign grp_fu_985_p10 = p_Result_4_1_2_1_reg_1227_pp0_iter1_reg;

assign grp_fu_994_p0 = sext_ln69_fu_451_p1;

assign grp_fu_994_p1 = grp_fu_994_p10;

assign grp_fu_994_p10 = p_Result_4_2_reg_1237_pp0_iter1_reg;

assign icmp_ln886_1_fu_776_p2 = (($signed(tmp_9_reg_1645) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_828_p2 = (($signed(tmp_11_reg_1661) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_724_p2 = (($signed(tmp_reg_1629) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign or_ln878_1_fu_814_p2 = (icmp_ln886_1_fu_776_p2 | and_ln878_1_fu_790_p2);

assign or_ln878_2_fu_866_p2 = (icmp_ln886_2_fu_828_p2 | and_ln878_2_fu_842_p2);

assign or_ln878_3_fu_748_p2 = (xor_ln878_fu_743_p2 | icmp_ln886_fu_724_p2);

assign or_ln878_4_fu_800_p2 = (xor_ln878_1_fu_795_p2 | icmp_ln886_1_fu_776_p2);

assign or_ln878_5_fu_852_p2 = (xor_ln878_2_fu_847_p2 | icmp_ln886_2_fu_828_p2);

assign or_ln878_fu_762_p2 = (icmp_ln886_fu_724_p2 | and_ln878_fu_738_p2);

assign out_1_2_fu_880_p4 = {{{select_ln878_5_fu_872_p3}, {select_ln878_3_fu_820_p3}}, {select_ln878_1_fu_768_p3}};

assign p_Result_4_1_0_1_fu_254_p4 = {{p_read7_int_reg[15:8]}};

assign p_Result_4_1_0_2_fu_268_p4 = {{p_read6_int_reg[15:8]}};

assign p_Result_4_1_2_fu_312_p4 = {{p_read2_int_reg[15:8]}};

assign p_Result_4_2_0_1_fu_356_p4 = {{p_read7_int_reg[23:16]}};

assign p_Result_4_2_0_2_fu_370_p4 = {{p_read6_int_reg[23:16]}};

assign p_Result_4_2_2_fu_414_p4 = {{p_read2_int_reg[23:16]}};

assign select_ln878_1_fu_768_p3 = ((or_ln878_fu_762_p2[0:0] == 1'b1) ? select_ln878_fu_754_p3 : trunc_ln215_fu_729_p1);

assign select_ln878_2_fu_806_p3 = ((or_ln878_4_fu_800_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln878_3_fu_820_p3 = ((or_ln878_1_fu_814_p2[0:0] == 1'b1) ? select_ln878_2_fu_806_p3 : trunc_ln215_1_fu_781_p1);

assign select_ln878_4_fu_858_p3 = ((or_ln878_5_fu_852_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln878_5_fu_872_p3 = ((or_ln878_2_fu_866_p2[0:0] == 1'b1) ? select_ln878_4_fu_858_p3 : trunc_ln215_2_fu_833_p1);

assign select_ln878_fu_754_p3 = ((or_ln878_3_fu_748_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign sext_ln1519_1_fu_670_p1 = add_ln69_15_reg_1614;

assign sext_ln1519_2_fu_697_p1 = add_ln69_23_reg_1619;

assign sext_ln1519_fu_643_p1 = add_ln69_7_reg_1609;

assign sext_ln674_1_fu_544_p1 = add_ln69_reg_1482;

assign sext_ln674_5_fu_566_p1 = add_ln69_8_reg_1497;

assign sext_ln674_9_fu_585_p1 = add_ln69_16_reg_1512;

assign sext_ln69_10_fu_232_p1 = $signed(p_read15_int_reg);

assign sext_ln69_11_fu_463_p1 = $signed(p_read_11_reg_1101_pp0_iter1_reg);

assign sext_ln69_14_fu_604_p1 = add_ln69_5_reg_1532_pp0_iter7_reg;

assign sext_ln69_15_fu_563_p1 = $signed(p_read_10_reg_1096_pp0_iter5_reg);

assign sext_ln69_19_fu_569_p1 = add_ln69_9_reg_1502;

assign sext_ln69_1_fu_196_p1 = $signed(p_read10_int_reg);

assign sext_ln69_23_fu_616_p1 = add_ln69_13_reg_1554_pp0_iter7_reg;

assign sext_ln69_27_fu_588_p1 = add_ln69_17_reg_1517;

assign sext_ln69_31_fu_628_p1 = add_ln69_21_reg_1569_pp0_iter7_reg;

assign sext_ln69_3_fu_208_p1 = $signed(p_read11_int_reg);

assign sext_ln69_4_fu_457_p1 = $signed(p_read_15_reg_1116_pp0_iter1_reg);

assign sext_ln69_6_fu_547_p1 = add_ln69_1_reg_1487;

assign sext_ln69_7_fu_505_p1 = $signed(p_read_14_reg_1111_pp0_iter3_reg);

assign sext_ln69_9_fu_487_p1 = $signed(p_read_13_reg_1106_pp0_iter2_reg);

assign sext_ln69_fu_451_p1 = $signed(p_read_18_reg_1121_pp0_iter1_reg);

assign trunc_ln215_1_fu_781_p1 = ashr_ln1519_1_reg_1640[7:0];

assign trunc_ln215_2_fu_833_p1 = ashr_ln1519_2_reg_1656[7:0];

assign trunc_ln215_fu_729_p1 = ashr_ln1519_reg_1624[7:0];

assign trunc_ln674_1_fu_188_p1 = p_read7_int_reg[7:0];

assign trunc_ln674_2_fu_200_p1 = p_read6_int_reg[7:0];

assign trunc_ln674_3_fu_212_p1 = p_read5_int_reg[7:0];

assign trunc_ln674_4_fu_216_p1 = p_read4_int_reg[7:0];

assign trunc_ln674_5_fu_220_p1 = p_read3_int_reg[7:0];

assign trunc_ln674_6_fu_224_p1 = p_read2_int_reg[7:0];

assign trunc_ln674_7_fu_236_p1 = p_read1_int_reg[7:0];

assign trunc_ln674_8_fu_240_p1 = p_read_int_reg[7:0];

assign trunc_ln674_fu_184_p1 = p_read8_int_reg[7:0];

assign xor_ln878_1_fu_795_p2 = (tmp_10_reg_1650 ^ 1'd1);

assign xor_ln878_2_fu_847_p2 = (tmp_12_reg_1666 ^ 1'd1);

assign xor_ln878_fu_743_p2 = (tmp_8_reg_1634 ^ 1'd1);

assign xor_ln886_1_fu_784_p2 = (icmp_ln886_1_fu_776_p2 ^ 1'd1);

assign xor_ln886_2_fu_836_p2 = (icmp_ln886_2_fu_828_p2 ^ 1'd1);

assign xor_ln886_fu_732_p2 = (icmp_ln886_fu_724_p2 ^ 1'd1);

endmodule //filter2d_accel_xFApplyFilter2D_15_15_3_3_3_s
