# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == composable_pr_0_dilate_erode || REF_NAME == composable_pr_0_dilate_erode}]
set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == composable_pr_1_dilate_erode || REF_NAME == composable_pr_1_dilate_erode}]
set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == composable_pr_fork_duplicate || REF_NAME == composable_pr_fork_duplicate}]
set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == composable_pr_join_subtract || REF_NAME == composable_pr_join_subtract}]
