// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_xFSobelFilter3x3_0_2_1080_1920_1_0_3_1_1_5_1920_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_419_dout,
        img_in_419_empty_n,
        img_in_419_read,
        gradx_mat_49_din,
        gradx_mat_49_full_n,
        gradx_mat_49_write,
        grady_mat_410_din,
        grady_mat_410_full_n,
        grady_mat_410_write,
        img_height,
        img_width
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_pp0_stage0 = 9'd2;
parameter    ap_ST_fsm_state5 = 9'd4;
parameter    ap_ST_fsm_state6 = 9'd8;
parameter    ap_ST_fsm_state7 = 9'd16;
parameter    ap_ST_fsm_pp1_stage0 = 9'd32;
parameter    ap_ST_fsm_state16 = 9'd64;
parameter    ap_ST_fsm_state17 = 9'd128;
parameter    ap_ST_fsm_state18 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] img_in_419_dout;
input   img_in_419_empty_n;
output   img_in_419_read;
output  [15:0] gradx_mat_49_din;
input   gradx_mat_49_full_n;
output   gradx_mat_49_write;
output  [15:0] grady_mat_410_din;
input   grady_mat_410_full_n;
output   grady_mat_410_write;
input  [15:0] img_height;
input  [15:0] img_width;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_in_419_read;
reg[15:0] gradx_mat_49_din;
reg gradx_mat_49_write;
reg[15:0] grady_mat_410_din;
reg grady_mat_410_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_in_419_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln878_reg_689;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln878_2_reg_756;
reg   [0:0] cmp_i_i517_i_reg_743;
reg    gradx_mat_49_blk_n;
reg    ap_enable_reg_pp1_iter7;
reg   [0:0] icmp_ln870_2_reg_778;
reg   [0:0] icmp_ln870_2_reg_778_pp1_iter6_reg;
wire    ap_CS_fsm_state18;
reg    grady_mat_410_blk_n;
reg   [12:0] col_V_reg_245;
reg   [12:0] col_V_2_reg_281;
reg   [12:0] col_V_2_reg_281_pp1_iter1_reg;
wire    ap_block_state8_pp1_stage0_iter0;
reg    ap_predicate_op95_read_state9;
reg    ap_block_state9_pp1_stage0_iter1;
wire    ap_block_state10_pp1_stage0_iter2;
wire    ap_block_state11_pp1_stage0_iter3;
wire    ap_block_state12_pp1_stage0_iter4;
wire    ap_block_state13_pp1_stage0_iter5;
wire    ap_block_state14_pp1_stage0_iter6;
reg    ap_block_state15_pp1_stage0_iter7;
reg    ap_block_pp1_stage0_11001;
reg   [12:0] col_V_2_reg_281_pp1_iter2_reg;
reg   [7:0] p_Val2_2_reg_293;
reg   [7:0] p_Val2_1_reg_305;
reg   [7:0] src_buf3_V_0_reg_317;
reg   [7:0] src_buf1_V_0_reg_330;
reg   [7:0] p_Val2_s_reg_342;
reg   [7:0] src_buf2_V_0_reg_355;
reg   [7:0] reg_426;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] col_V_3_fu_433_p2;
reg   [12:0] col_V_3_reg_684;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln878_fu_443_p2;
reg   [0:0] icmp_ln878_reg_689_pp0_iter1_reg;
wire   [63:0] zext_ln534_fu_448_p1;
reg   [63:0] zext_ln534_reg_693;
wire   [16:0] op2_assign_fu_456_p2;
reg   [16:0] op2_assign_reg_723;
wire    ap_CS_fsm_state5;
wire   [15:0] zext_ln878_1_fu_471_p1;
reg   [15:0] zext_ln878_1_reg_731;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln878_1_fu_466_p2;
wire   [0:0] icmp_ln870_fu_505_p2;
reg   [0:0] icmp_ln870_reg_736;
wire   [12:0] ap_phi_mux_row_ind_V_phi_fu_273_p4;
wire   [0:0] cmp_i_i517_i_fu_547_p2;
wire    ap_CS_fsm_state7;
wire   [1:0] trunc_ln228_fu_551_p1;
reg   [1:0] trunc_ln228_reg_747;
wire   [12:0] col_V_4_fu_555_p2;
reg   [12:0] col_V_4_reg_751;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln878_2_fu_565_p2;
reg   [0:0] icmp_ln878_2_reg_756_pp1_iter1_reg;
reg   [0:0] icmp_ln878_2_reg_756_pp1_iter2_reg;
reg   [0:0] icmp_ln878_2_reg_756_pp1_iter3_reg;
reg   [0:0] icmp_ln878_2_reg_756_pp1_iter4_reg;
reg   [0:0] icmp_ln878_2_reg_756_pp1_iter5_reg;
wire   [0:0] icmp_ln870_2_fu_591_p2;
reg   [0:0] icmp_ln870_2_reg_778_pp1_iter4_reg;
reg   [0:0] icmp_ln870_2_reg_778_pp1_iter5_reg;
wire   [7:0] buf_V_0_q0;
reg   [7:0] buf_V_0_load_reg_782;
reg    ap_enable_reg_pp1_iter4;
wire   [7:0] buf_V_1_q0;
reg   [7:0] buf_V_1_load_reg_789;
wire   [7:0] buf_V_2_q0;
reg   [7:0] buf_V_2_load_reg_796;
wire   [7:0] src_buf1_V_2_fu_600_p5;
reg   [7:0] src_buf1_V_2_reg_803;
reg    ap_enable_reg_pp1_iter5;
wire   [7:0] src_buf2_V_2_fu_610_p5;
reg   [7:0] src_buf2_V_2_reg_809;
wire   [7:0] src_buf3_V_2_fu_620_p5;
reg   [7:0] src_buf3_V_2_reg_815;
reg   [15:0] GradientValuesX_V_0_reg_821;
reg   [15:0] GradientValuesY_V_0_reg_826;
wire   [12:0] row_V_3_fu_638_p2;
reg   [12:0] row_V_3_reg_831;
wire    ap_CS_fsm_state16;
wire   [12:0] row_ind_V_2_fu_656_p3;
reg   [12:0] row_ind_V_2_reg_836;
wire   [10:0] grp_xFGradientX3x3_0_3_s_fu_385_ap_return;
reg   [10:0] tmp_reg_841;
wire    ap_CS_fsm_state17;
wire   [10:0] grp_xFGradientY3x3_0_3_s_fu_401_ap_return;
reg   [10:0] tmp_1_reg_846;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter6;
reg    ap_condition_pp1_exit_iter5_state13;
wire   [10:0] buf_V_0_address0;
reg    buf_V_0_ce0;
reg   [10:0] buf_V_0_address1;
reg    buf_V_0_ce1;
reg    buf_V_0_we1;
reg   [7:0] buf_V_0_d1;
wire   [10:0] buf_V_1_address0;
reg    buf_V_1_ce0;
reg   [10:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [7:0] buf_V_1_d1;
wire   [10:0] buf_V_2_address0;
reg    buf_V_2_ce0;
reg   [10:0] buf_V_2_address1;
reg    buf_V_2_ce1;
reg    buf_V_2_we1;
reg   [7:0] buf_V_2_d1;
wire   [15:0] grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_0;
wire   [15:0] grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_1;
reg    grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_ce;
wire    ap_block_state8_pp1_stage0_iter0_ignore_call13;
reg    ap_block_state9_pp1_stage0_iter1_ignore_call13;
wire    ap_block_state10_pp1_stage0_iter2_ignore_call13;
wire    ap_block_state11_pp1_stage0_iter3_ignore_call13;
wire    ap_block_state12_pp1_stage0_iter4_ignore_call13;
wire    ap_block_state13_pp1_stage0_iter5_ignore_call13;
wire    ap_block_state14_pp1_stage0_iter6_ignore_call13;
reg    ap_block_state15_pp1_stage0_iter7_ignore_call13;
reg    ap_block_pp1_stage0_11001_ignoreCallOp142;
reg    grp_xFGradientX3x3_0_3_s_fu_385_ap_ce;
reg    grp_xFGradientY3x3_0_3_s_fu_401_ap_ce;
reg   [12:0] ap_phi_mux_col_V_phi_fu_249_p4;
reg   [12:0] row_V_reg_257;
reg    ap_block_state18;
reg   [12:0] row_ind_V_reg_269;
reg   [12:0] ap_phi_mux_col_V_2_phi_fu_285_p4;
reg   [7:0] ap_phi_mux_p_Val2_2_phi_fu_297_p4;
reg   [7:0] ap_phi_mux_p_Val2_1_phi_fu_309_p4;
reg   [7:0] ap_phi_mux_src_buf3_V_0_phi_fu_322_p4;
reg   [7:0] ap_phi_mux_src_buf1_V_0_phi_fu_334_p4;
reg   [7:0] ap_phi_mux_p_Val2_s_phi_fu_346_p4;
wire   [63:0] zext_ln534_2_fu_570_p1;
wire   [63:0] zext_ln534_1_fu_577_p1;
wire   [63:0] zext_ln231_fu_584_p1;
reg   [1:0] bottom_fu_94;
wire   [1:0] bottom_1_fu_511_p3;
wire   [1:0] grp_load_fu_417_p1;
reg   [1:0] mid_fu_98;
wire   [1:0] mid_1_fu_518_p3;
reg   [1:0] tp_fu_102;
wire   [1:0] tp_1_fu_525_p3;
reg    ap_block_pp1_stage0_01001;
wire  signed [15:0] sext_ln413_fu_664_p1;
wire  signed [15:0] sext_ln413_1_fu_668_p1;
wire   [15:0] zext_ln878_fu_439_p1;
wire   [16:0] img_height_cast_fu_453_p1;
wire   [16:0] zext_ln878_2_fu_462_p1;
wire   [15:0] zext_ln878_3_fu_561_p1;
wire   [12:0] row_ind_V_1_fu_644_p2;
wire   [0:0] icmp_ln870_1_fu_650_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_711;
reg    ap_condition_715;
reg    ap_condition_709;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
end

cornerHarris_accel_xFSobelFilter3x3_0_2_1080_1920_1_0_3_1_1_5_1920_false_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_0_address0),
    .ce0(buf_V_0_ce0),
    .q0(buf_V_0_q0),
    .address1(buf_V_0_address1),
    .ce1(buf_V_0_ce1),
    .we1(buf_V_0_we1),
    .d1(buf_V_0_d1)
);

cornerHarris_accel_xFSobelFilter3x3_0_2_1080_1920_1_0_3_1_1_5_1920_false_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

cornerHarris_accel_xFSobelFilter3x3_0_2_1080_1920_1_0_3_1_1_5_1920_false_s_buf_V_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_2_address0),
    .ce0(buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(buf_V_2_address1),
    .ce1(buf_V_2_ce1),
    .we1(buf_V_2_we1),
    .d1(buf_V_2_d1)
);

cornerHarris_accel_xFSobel3x3_1_1_0_3_s grp_xFSobel3x3_1_1_0_3_s_fu_368(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read2(ap_phi_mux_p_Val2_s_phi_fu_346_p4),
    .p_read5(ap_phi_mux_src_buf1_V_0_phi_fu_334_p4),
    .p_read6(src_buf1_V_2_fu_600_p5),
    .p_read7(ap_phi_mux_p_Val2_1_phi_fu_309_p4),
    .p_read8(src_buf2_V_2_fu_610_p5),
    .p_read9(ap_phi_mux_p_Val2_2_phi_fu_297_p4),
    .p_read10(ap_phi_mux_src_buf3_V_0_phi_fu_322_p4),
    .p_read11(src_buf3_V_2_fu_620_p5),
    .ap_return_0(grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_0),
    .ap_return_1(grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_1),
    .ap_ce(grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_ce)
);

cornerHarris_accel_xFGradientX3x3_0_3_s grp_xFGradientX3x3_0_3_s_fu_385(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(p_Val2_s_reg_342),
    .t2(8'd0),
    .m0(p_Val2_1_reg_305),
    .m2(8'd0),
    .b0(p_Val2_2_reg_293),
    .b2(8'd0),
    .ap_return(grp_xFGradientX3x3_0_3_s_fu_385_ap_return),
    .ap_ce(grp_xFGradientX3x3_0_3_s_fu_385_ap_ce)
);

cornerHarris_accel_xFGradientY3x3_0_3_s grp_xFGradientY3x3_0_3_s_fu_401(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0(p_Val2_s_reg_342),
    .t1(src_buf1_V_0_reg_330),
    .t2(8'd0),
    .b0(p_Val2_2_reg_293),
    .b1(src_buf3_V_0_reg_317),
    .b2(8'd0),
    .ap_return(grp_xFGradientY3x3_0_3_s_fu_401_ap_return),
    .ap_ce(grp_xFGradientY3x3_0_3_s_fu_401_ap_ce)
);

cornerHarris_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U74(
    .din0(buf_V_0_load_reg_782),
    .din1(buf_V_1_load_reg_789),
    .din2(buf_V_2_load_reg_796),
    .din3(tp_fu_102),
    .dout(src_buf1_V_2_fu_600_p5)
);

cornerHarris_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U75(
    .din0(buf_V_0_load_reg_782),
    .din1(buf_V_1_load_reg_789),
    .din2(buf_V_2_load_reg_796),
    .din3(mid_fu_98),
    .dout(src_buf2_V_2_fu_610_p5)
);

cornerHarris_accel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_32_8_1_1_U76(
    .din0(buf_V_0_load_reg_782),
    .din1(buf_V_1_load_reg_789),
    .din2(buf_V_2_load_reg_796),
    .din3(bottom_fu_94),
    .dout(src_buf3_V_2_fu_620_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter5_state13)) begin
                ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter4;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp1_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd2) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        bottom_fu_94 <= 2'd2;
    end else if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd0) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        bottom_fu_94 <= 2'd0;
    end else if ((~(row_ind_V_reg_269 == 13'd0) & ~(row_ind_V_reg_269 == 13'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        bottom_fu_94 <= bottom_1_fu_511_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_2_reg_756 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        col_V_2_reg_281 <= col_V_4_reg_751;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        col_V_2_reg_281 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        col_V_reg_245 <= col_V_3_reg_684;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_V_reg_245 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd2) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        mid_fu_98 <= 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd0) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        mid_fu_98 <= 2'd2;
    end else if ((~(row_ind_V_reg_269 == 13'd0) & ~(row_ind_V_reg_269 == 13'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        mid_fu_98 <= mid_1_fu_518_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        p_Val2_1_reg_305 <= src_buf2_V_0_reg_355;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_1_reg_305 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        p_Val2_2_reg_293 <= src_buf3_V_0_reg_317;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_2_reg_293 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        p_Val2_s_reg_342 <= src_buf1_V_0_reg_330;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_s_reg_342 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        row_V_reg_257 <= row_V_3_reg_831;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        row_V_reg_257 <= 13'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        row_ind_V_reg_269 <= row_ind_V_2_reg_836;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        row_ind_V_reg_269 <= 13'd2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        src_buf1_V_0_reg_330 <= src_buf1_V_2_reg_803;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        src_buf1_V_0_reg_330 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        src_buf2_V_0_reg_355 <= src_buf2_V_2_reg_809;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        src_buf2_V_0_reg_355 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        src_buf3_V_0_reg_317 <= src_buf3_V_2_reg_815;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        src_buf3_V_0_reg_317 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd2) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        tp_fu_102 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd0) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        tp_fu_102 <= 2'd1;
    end else if ((~(row_ind_V_reg_269 == 13'd0) & ~(row_ind_V_reg_269 == 13'd2) & (1'b1 == ap_CS_fsm_state7))) begin
        tp_fu_102 <= tp_1_fu_525_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        GradientValuesX_V_0_reg_821 <= grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_0;
        GradientValuesY_V_0_reg_826 <= grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter4 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter3_reg == 1'd1))) begin
        buf_V_0_load_reg_782 <= buf_V_0_q0;
        buf_V_1_load_reg_789 <= buf_V_1_q0;
        buf_V_2_load_reg_796 <= buf_V_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        cmp_i_i517_i_reg_743 <= cmp_i_i517_i_fu_547_p2;
        trunc_ln228_reg_747 <= trunc_ln228_fu_551_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        col_V_2_reg_281_pp1_iter1_reg <= col_V_2_reg_281;
        icmp_ln878_2_reg_756 <= icmp_ln878_2_fu_565_p2;
        icmp_ln878_2_reg_756_pp1_iter1_reg <= icmp_ln878_2_reg_756;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        col_V_2_reg_281_pp1_iter2_reg <= col_V_2_reg_281_pp1_iter1_reg;
        icmp_ln870_2_reg_778_pp1_iter4_reg <= icmp_ln870_2_reg_778;
        icmp_ln870_2_reg_778_pp1_iter5_reg <= icmp_ln870_2_reg_778_pp1_iter4_reg;
        icmp_ln870_2_reg_778_pp1_iter6_reg <= icmp_ln870_2_reg_778_pp1_iter5_reg;
        icmp_ln878_2_reg_756_pp1_iter2_reg <= icmp_ln878_2_reg_756_pp1_iter1_reg;
        icmp_ln878_2_reg_756_pp1_iter3_reg <= icmp_ln878_2_reg_756_pp1_iter2_reg;
        icmp_ln878_2_reg_756_pp1_iter4_reg <= icmp_ln878_2_reg_756_pp1_iter3_reg;
        icmp_ln878_2_reg_756_pp1_iter5_reg <= icmp_ln878_2_reg_756_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        col_V_3_reg_684 <= col_V_3_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        col_V_4_reg_751 <= col_V_4_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln878_2_reg_756_pp1_iter2_reg == 1'd1))) begin
        icmp_ln870_2_reg_778 <= icmp_ln870_2_fu_591_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd0) & ~(ap_phi_mux_row_ind_V_phi_fu_273_p4 == 13'd2) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        icmp_ln870_reg_736 <= icmp_ln870_fu_505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln878_reg_689 <= icmp_ln878_fu_443_p2;
        icmp_ln878_reg_689_pp0_iter1_reg <= icmp_ln878_reg_689;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        op2_assign_reg_723 <= op2_assign_fu_456_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_predicate_op95_read_state9 == 1'b1)) | ((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_426 <= img_in_419_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        row_V_3_reg_831 <= row_V_3_fu_638_p2;
        row_ind_V_2_reg_836 <= row_ind_V_2_fu_656_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter5 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter4_reg == 1'd1))) begin
        src_buf1_V_2_reg_803 <= src_buf1_V_2_fu_600_p5;
        src_buf2_V_2_reg_809 <= src_buf2_V_2_fu_610_p5;
        src_buf3_V_2_reg_815 <= src_buf3_V_2_fu_620_p5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_1_reg_846 <= grp_xFGradientY3x3_0_3_s_fu_401_ap_return;
        tmp_reg_841 <= grp_xFGradientX3x3_0_3_s_fu_385_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln534_reg_693[12 : 0] <= zext_ln534_fu_448_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln878_1_fu_466_p2 == 1'd1))) begin
        zext_ln878_1_reg_731[12 : 0] <= zext_ln878_1_fu_471_p1[12 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln878_fu_443_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0))) begin
        ap_condition_pp1_exit_iter5_state13 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter5_state13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln878_2_fu_565_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln878_1_fu_466_p2 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_2_reg_756 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_col_V_2_phi_fu_285_p4 = col_V_4_reg_751;
    end else begin
        ap_phi_mux_col_V_2_phi_fu_285_p4 = col_V_2_reg_281;
    end
end

always @ (*) begin
    if (((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_col_V_phi_fu_249_p4 = col_V_3_reg_684;
    end else begin
        ap_phi_mux_col_V_phi_fu_249_p4 = col_V_reg_245;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_1_phi_fu_309_p4 = src_buf2_V_0_reg_355;
    end else begin
        ap_phi_mux_p_Val2_1_phi_fu_309_p4 = p_Val2_1_reg_305;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_2_phi_fu_297_p4 = src_buf3_V_0_reg_317;
    end else begin
        ap_phi_mux_p_Val2_2_phi_fu_297_p4 = p_Val2_2_reg_293;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_s_phi_fu_346_p4 = src_buf1_V_0_reg_330;
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_346_p4 = p_Val2_s_reg_342;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        ap_phi_mux_src_buf1_V_0_phi_fu_334_p4 = src_buf1_V_2_reg_803;
    end else begin
        ap_phi_mux_src_buf1_V_0_phi_fu_334_p4 = src_buf1_V_0_reg_330;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter5_reg == 1'd1))) begin
        ap_phi_mux_src_buf3_V_0_phi_fu_322_p4 = src_buf3_V_2_reg_815;
    end else begin
        ap_phi_mux_src_buf3_V_0_phi_fu_322_p4 = src_buf3_V_0_reg_317;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln878_1_fu_466_p2 == 1'd0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd0))) begin
        buf_V_0_address1 = zext_ln534_1_fu_577_p1;
    end else if (((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (grp_load_fu_417_p1 == 2'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1))) begin
        buf_V_0_address1 = zext_ln534_2_fu_570_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_V_0_address1 = zext_ln534_fu_448_p1;
    end else begin
        buf_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        buf_V_0_ce0 = 1'b1;
    end else begin
        buf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd0)) | ((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (grp_load_fu_417_p1 == 2'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_V_0_ce1 = 1'b1;
    end else begin
        buf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd0))) begin
        buf_V_0_d1 = reg_426;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (grp_load_fu_417_p1 == 2'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)))) begin
        buf_V_0_d1 = 8'd0;
    end else begin
        buf_V_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd0)) | ((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (grp_load_fu_417_p1 == 2'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)))) begin
        buf_V_0_we1 = 1'b1;
    end else begin
        buf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd1))) begin
        buf_V_1_address1 = zext_ln534_1_fu_577_p1;
    end else if (((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (grp_load_fu_417_p1 == 2'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1))) begin
        buf_V_1_address1 = zext_ln534_2_fu_570_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        buf_V_1_address1 = zext_ln534_reg_693;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd1)) | ((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (grp_load_fu_417_p1 == 2'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (grp_load_fu_417_p1 == 2'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1))) begin
        buf_V_1_d1 = 8'd0;
    end else if ((((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        buf_V_1_d1 = reg_426;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1) & (trunc_ln228_reg_747 == 2'd1)) | ((cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (grp_load_fu_417_p1 == 2'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln878_reg_689_pp0_iter1_reg == 1'd1)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_709)) begin
        if ((1'b1 == ap_condition_715)) begin
            buf_V_2_address1 = zext_ln534_1_fu_577_p1;
        end else if ((1'b1 == ap_condition_711)) begin
            buf_V_2_address1 = zext_ln534_2_fu_570_p1;
        end else begin
            buf_V_2_address1 = 'bx;
        end
    end else begin
        buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln228_reg_747 == 2'd1) & ~(trunc_ln228_reg_747 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)) | (~(grp_load_fu_417_p1 == 2'd1) & ~(grp_load_fu_417_p1 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_709)) begin
        if ((1'b1 == ap_condition_715)) begin
            buf_V_2_d1 = reg_426;
        end else if ((1'b1 == ap_condition_711)) begin
            buf_V_2_d1 = 8'd0;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln228_reg_747 == 2'd1) & ~(trunc_ln228_reg_747 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)) | (~(grp_load_fu_417_p1 == 2'd1) & ~(grp_load_fu_417_p1 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        gradx_mat_49_blk_n = gradx_mat_49_full_n;
    end else begin
        gradx_mat_49_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        gradx_mat_49_din = sext_ln413_fu_664_p1;
    end else if (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_01001))) begin
        gradx_mat_49_din = GradientValuesX_V_0_reg_821;
    end else begin
        gradx_mat_49_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | (~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)))) begin
        gradx_mat_49_write = 1'b1;
    end else begin
        gradx_mat_49_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0)))) begin
        grady_mat_410_blk_n = grady_mat_410_full_n;
    end else begin
        grady_mat_410_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
        grady_mat_410_din = sext_ln413_1_fu_668_p1;
    end else if (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_01001))) begin
        grady_mat_410_din = GradientValuesY_V_0_reg_826;
    end else begin
        grady_mat_410_din = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | (~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18)))) begin
        grady_mat_410_write = 1'b1;
    end else begin
        grady_mat_410_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        grp_xFGradientX3x3_0_3_s_fu_385_ap_ce = 1'b1;
    end else begin
        grp_xFGradientX3x3_0_3_s_fu_385_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        grp_xFGradientY3x3_0_3_s_fu_401_ap_ce = 1'b1;
    end else begin
        grp_xFGradientY3x3_0_3_s_fu_401_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001_ignoreCallOp142) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_ce = 1'b1;
    end else begin
        grp_xFSobel3x3_1_1_0_3_s_fu_368_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i517_i_reg_743 == 1'd1) & (icmp_ln878_2_reg_756 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_in_419_blk_n = img_in_419_empty_n;
    end else begin
        img_in_419_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_predicate_op95_read_state9 == 1'b1)) | ((icmp_ln878_reg_689 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        img_in_419_read = 1'b1;
    end else begin
        img_in_419_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln878_fu_443_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln878_fu_443_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln878_1_fu_466_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0)) & ~((ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter7 == 1'b1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b0)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (ap_enable_reg_pp1_iter4 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if ((~((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((icmp_ln878_reg_689 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((icmp_ln878_reg_689 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((ap_enable_reg_pp1_iter7 == 1'b1) & (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)))) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_enable_reg_pp1_iter7 == 1'b1) & (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)))) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001_ignoreCallOp142 = (((ap_enable_reg_pp1_iter7 == 1'b1) & (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)))) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_enable_reg_pp1_iter7 == 1'b1) & (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)))) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1)));
end

assign ap_block_state10_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage0_iter2_ignore_call13 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter3_ignore_call13 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter4_ignore_call13 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter5_ignore_call13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter6_ignore_call13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state15_pp1_stage0_iter7 = (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state15_pp1_stage0_iter7_ignore_call13 = (((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (grady_mat_410_full_n == 1'b0)) | ((icmp_ln870_2_reg_778_pp1_iter6_reg == 1'd0) & (gradx_mat_49_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state18 = ((grady_mat_410_full_n == 1'b0) | (gradx_mat_49_full_n == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln878_reg_689 == 1'd1) & (img_in_419_empty_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter0_ignore_call13 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp1_stage0_iter1 = ((img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1));
end

always @ (*) begin
    ap_block_state9_pp1_stage0_iter1_ignore_call13 = ((img_in_419_empty_n == 1'b0) & (ap_predicate_op95_read_state9 == 1'b1));
end

always @ (*) begin
    ap_condition_709 = ((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_2_reg_756_pp1_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_condition_711 = (~(grp_load_fu_417_p1 == 2'd1) & ~(grp_load_fu_417_p1 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd0));
end

always @ (*) begin
    ap_condition_715 = (~(trunc_ln228_reg_747 == 2'd1) & ~(trunc_ln228_reg_747 == 2'd0) & (cmp_i_i517_i_reg_743 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_row_ind_V_phi_fu_273_p4 = row_ind_V_reg_269;

always @ (*) begin
    ap_predicate_op95_read_state9 = ((cmp_i_i517_i_reg_743 == 1'd1) & (icmp_ln878_2_reg_756 == 1'd1));
end

assign bottom_1_fu_511_p3 = ((icmp_ln870_reg_736[0:0] == 1'b1) ? 2'd1 : bottom_fu_94);

assign buf_V_0_address0 = zext_ln231_fu_584_p1;

assign buf_V_1_address0 = zext_ln231_fu_584_p1;

assign buf_V_2_address0 = zext_ln231_fu_584_p1;

assign cmp_i_i517_i_fu_547_p2 = ((zext_ln878_1_reg_731 < img_height) ? 1'b1 : 1'b0);

assign col_V_3_fu_433_p2 = (ap_phi_mux_col_V_phi_fu_249_p4 + 13'd1);

assign col_V_4_fu_555_p2 = (ap_phi_mux_col_V_2_phi_fu_285_p4 + 13'd1);

assign grp_load_fu_417_p1 = bottom_fu_94;

assign icmp_ln870_1_fu_650_p2 = ((row_ind_V_1_fu_644_p2 == 13'd3) ? 1'b1 : 1'b0);

assign icmp_ln870_2_fu_591_p2 = ((col_V_2_reg_281_pp1_iter2_reg == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln870_fu_505_p2 = ((row_ind_V_reg_269 == 13'd1) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_466_p2 = ((zext_ln878_2_fu_462_p1 < op2_assign_reg_723) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_565_p2 = ((zext_ln878_3_fu_561_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_443_p2 = ((zext_ln878_fu_439_p1 < img_width) ? 1'b1 : 1'b0);

assign img_height_cast_fu_453_p1 = img_height;

assign mid_1_fu_518_p3 = ((icmp_ln870_reg_736[0:0] == 1'b1) ? 2'd0 : mid_fu_98);

assign op2_assign_fu_456_p2 = (img_height_cast_fu_453_p1 + 17'd1);

assign row_V_3_fu_638_p2 = (row_V_reg_257 + 13'd1);

assign row_ind_V_1_fu_644_p2 = (row_ind_V_reg_269 + 13'd1);

assign row_ind_V_2_fu_656_p3 = ((icmp_ln870_1_fu_650_p2[0:0] == 1'b1) ? 13'd0 : row_ind_V_1_fu_644_p2);

assign sext_ln413_1_fu_668_p1 = $signed(tmp_1_reg_846);

assign sext_ln413_fu_664_p1 = $signed(tmp_reg_841);

assign tp_1_fu_525_p3 = ((icmp_ln870_reg_736[0:0] == 1'b1) ? 2'd2 : tp_fu_102);

assign trunc_ln228_fu_551_p1 = row_ind_V_reg_269[1:0];

assign zext_ln231_fu_584_p1 = col_V_2_reg_281_pp1_iter2_reg;

assign zext_ln534_1_fu_577_p1 = col_V_2_reg_281_pp1_iter1_reg;

assign zext_ln534_2_fu_570_p1 = col_V_2_reg_281_pp1_iter1_reg;

assign zext_ln534_fu_448_p1 = col_V_reg_245;

assign zext_ln878_1_fu_471_p1 = row_V_reg_257;

assign zext_ln878_2_fu_462_p1 = row_V_reg_257;

assign zext_ln878_3_fu_561_p1 = ap_phi_mux_col_V_2_phi_fu_285_p4;

assign zext_ln878_fu_439_p1 = ap_phi_mux_col_V_phi_fu_249_p4;

always @ (posedge ap_clk) begin
    zext_ln534_reg_693[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
    zext_ln878_1_reg_731[15:13] <= 3'b000;
end

endmodule //cornerHarris_accel_xFSobelFilter3x3_0_2_1080_1920_1_0_3_1_1_5_1920_false_s
