# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.srcs/sources_1/bd/composable_pr_join_bitand/composable_pr_join_bitand.bd
# Block Designs: The module: 'composable_pr_join_bitand' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.srcs/sources_1/bd/composable_pr_join_bitand/ip/composable_pr_join_bitand_bitwise_and_accel_0/composable_pr_join_bitand_bitwise_and_accel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==composable_pr_join_bitand_bitwise_and_accel_0 || ORIG_REF_NAME==composable_pr_join_bitand_bitwise_and_accel_0} -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.gen/sources_1/bd/composable_pr_join_bitand/composable_pr_join_bitand_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'composable_pr_join_bitand'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.srcs/sources_1/bd/composable_pr_join_bitand/composable_pr_join_bitand.bd
# Block Designs: The module: 'composable_pr_join_bitand' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.srcs/sources_1/bd/composable_pr_join_bitand/ip/composable_pr_join_bitand_bitwise_and_accel_0/composable_pr_join_bitand_bitwise_and_accel_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==composable_pr_join_bitand_bitwise_and_accel_0 || ORIG_REF_NAME==composable_pr_join_bitand_bitwise_and_accel_0} -quiet] -quiet

# XDC: /home/willychiang/Desktop/PYNQ_Composable_Pipeline/boards/Pynq-Z2/cv_dfx_4_pr/cv_dfx_4_pr.gen/sources_1/bd/composable_pr_join_bitand/composable_pr_join_bitand_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'composable_pr_join_bitand'. Do not add the DONT_TOUCH constraint.
