// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module erode_accel_xferode_1080_1920_3_9_1_0_1921_3_3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_in_419_dout,
        img_in_419_empty_n,
        img_in_419_read,
        img_out_420_din,
        img_out_420_full_n,
        img_out_420_write,
        img_height,
        img_width,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_pp1_stage0 = 10'd8;
parameter    ap_ST_fsm_state7 = 10'd16;
parameter    ap_ST_fsm_pp2_stage0 = 10'd32;
parameter    ap_ST_fsm_state10 = 10'd64;
parameter    ap_ST_fsm_state11 = 10'd128;
parameter    ap_ST_fsm_pp3_stage0 = 10'd256;
parameter    ap_ST_fsm_state24 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_in_419_dout;
input   img_in_419_empty_n;
output   img_in_419_read;
output  [23:0] img_out_420_din;
input   img_out_420_full_n;
output   img_out_420_write;
input  [15:0] img_height;
input  [15:0] img_width;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_in_419_read;
reg img_out_420_write;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    img_in_419_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln878_reg_1626;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_pp3_stage0;
reg   [0:0] icmp_ln878_4_reg_1743;
reg   [0:0] icmp_ln878_5_reg_1747;
reg   [0:0] cmp_i_i127_i_reg_1720;
reg    img_out_420_blk_n;
reg    ap_enable_reg_pp3_iter11;
reg   [0:0] icmp_ln882_reg_1766;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter10_reg;
reg   [12:0] i_col_046_0_reg_347;
reg   [12:0] i_col_046_0_reg_347_pp1_iter1_reg;
wire    ap_block_state4_pp1_stage0_iter0;
reg    ap_block_state5_pp1_stage0_iter1;
wire    ap_block_state6_pp1_stage0_iter2;
reg    ap_block_pp1_stage0_11001;
reg   [12:0] i_col_V_0_reg_359;
reg   [12:0] col_V_reg_416;
reg   [12:0] col_V_reg_416_pp3_iter1_reg;
wire    ap_block_state12_pp3_stage0_iter0;
reg    ap_predicate_op142_read_state13;
reg    ap_block_state13_pp3_stage0_iter1;
wire    ap_block_state14_pp3_stage0_iter2;
wire    ap_block_state15_pp3_stage0_iter3;
wire    ap_block_state16_pp3_stage0_iter4;
wire    ap_block_state17_pp3_stage0_iter5;
wire    ap_block_state18_pp3_stage0_iter6;
wire    ap_block_state19_pp3_stage0_iter7;
wire    ap_block_state20_pp3_stage0_iter8;
wire    ap_block_state21_pp3_stage0_iter9;
wire    ap_block_state22_pp3_stage0_iter10;
reg    ap_block_state23_pp3_stage0_iter11;
reg    ap_block_pp3_stage0_11001;
reg   [12:0] col_V_reg_416_pp3_iter2_reg;
reg   [23:0] src_buf_V_0_0_reg_428;
reg   [23:0] p_Val2_s_reg_440;
reg   [23:0] src_buf_V_1_0_reg_475;
reg   [23:0] p_Val2_3_reg_487;
reg   [23:0] p_Val2_6_reg_510;
reg   [23:0] src_buf_V_2_0_reg_521;
reg   [23:0] reg_564;
wire   [13:0] empty_fu_572_p1;
reg   [13:0] empty_reg_1593;
wire   [1:0] init_row_ind_fu_576_p2;
wire    ap_CS_fsm_state2;
reg   [12:0] row_ind_V_0_0_load_reg_1603;
reg   [12:0] row_ind_V_1_0_load_reg_1608;
reg   [12:0] row_ind_V_2_0_load_reg_1613;
wire   [12:0] add_ln691_fu_616_p2;
reg   [12:0] add_ln691_reg_1621;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln878_fu_626_p2;
reg   [0:0] icmp_ln878_reg_1626_pp1_iter1_reg;
wire   [12:0] add_ln691_1_fu_636_p2;
reg   [12:0] add_ln691_1_reg_1630;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state8_pp2_stage0_iter0;
wire    ap_block_state9_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln878_1_fu_646_p2;
reg   [0:0] icmp_ln878_1_reg_1635;
wire   [16:0] op2_assign_fu_659_p2;
reg   [16:0] op2_assign_reg_1639;
wire    ap_CS_fsm_state10;
wire   [13:0] add_ln1616_fu_665_p2;
reg   [13:0] add_ln1616_reg_1644;
wire   [0:0] icmp_ln878_2_fu_680_p2;
reg   [0:0] icmp_ln878_2_reg_1649;
wire   [0:0] tobool_i_i_fu_686_p2;
reg   [0:0] tobool_i_i_reg_1653;
wire   [0:0] tobool_i_i_1126_fu_691_p2;
reg   [0:0] tobool_i_i_1126_reg_1660;
wire   [0:0] tobool_i_i_2135_fu_696_p2;
reg   [0:0] tobool_i_i_2135_reg_1667;
wire   [0:0] tobool_i_i_1106_fu_701_p2;
reg   [0:0] tobool_i_i_1106_reg_1674;
wire   [0:0] tobool_i_i_1106_1_fu_706_p2;
reg   [0:0] tobool_i_i_1106_1_reg_1681;
wire   [0:0] tobool_i_i_1106_2_fu_711_p2;
reg   [0:0] tobool_i_i_1106_2_reg_1688;
wire   [0:0] tobool_i_i_2114_fu_716_p2;
reg   [0:0] tobool_i_i_2114_reg_1695;
wire   [0:0] tobool_i_i_2114_1_fu_721_p2;
reg   [0:0] tobool_i_i_2114_1_reg_1702;
wire   [0:0] tobool_i_i_2114_2_fu_726_p2;
reg   [0:0] tobool_i_i_2114_2_reg_1709;
wire   [0:0] icmp_ln878_3_fu_739_p2;
wire    ap_CS_fsm_state11;
wire   [0:0] cmp_i_i127_i_fu_744_p2;
wire   [1:0] trunc_ln124_fu_749_p1;
reg   [1:0] trunc_ln124_reg_1724;
wire   [1:0] trunc_ln138_fu_753_p1;
reg   [1:0] trunc_ln138_reg_1728;
wire   [1:0] trunc_ln138_1_fu_757_p1;
reg   [1:0] trunc_ln138_1_reg_1733;
wire   [12:0] col_V_1_fu_761_p2;
reg   [12:0] col_V_1_reg_1738;
reg    ap_enable_reg_pp3_iter0;
wire   [0:0] icmp_ln878_4_fu_775_p2;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter1_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter2_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter3_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter4_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter5_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter6_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter7_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter8_reg;
reg   [0:0] icmp_ln878_4_reg_1743_pp3_iter9_reg;
wire   [0:0] icmp_ln878_5_fu_780_p2;
reg   [0:0] icmp_ln878_5_reg_1747_pp3_iter1_reg;
reg   [0:0] icmp_ln878_5_reg_1747_pp3_iter2_reg;
reg   [0:0] icmp_ln878_5_reg_1747_pp3_iter3_reg;
reg   [0:0] icmp_ln878_5_reg_1747_pp3_iter4_reg;
wire   [0:0] icmp_ln882_fu_806_p2;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter4_reg;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter5_reg;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter6_reg;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter7_reg;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter8_reg;
reg   [0:0] icmp_ln882_reg_1766_pp3_iter9_reg;
wire   [23:0] buf_V_0_q0;
reg   [23:0] buf_V_0_load_reg_1770;
reg    ap_enable_reg_pp3_iter4;
wire   [23:0] buf_V_1_q0;
reg   [23:0] buf_V_1_load_reg_1776;
wire   [23:0] buf_V_2_q0;
reg   [23:0] buf_V_2_load_reg_1782;
wire   [23:0] tmp_fu_821_p5;
wire   [23:0] src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return;
reg   [23:0] src_buf_V_0_1_reg_1793;
reg    ap_enable_reg_pp3_iter5;
wire   [7:0] max_V_1_fu_858_p3;
reg   [7:0] max_V_1_reg_1798;
wire   [7:0] p_Result_2_fu_865_p1;
reg   [7:0] p_Result_2_reg_1805;
wire   [7:0] max_V_10_fu_910_p3;
reg   [7:0] max_V_10_reg_1811;
reg   [7:0] p_Result_11_reg_1818;
wire   [7:0] max_V_19_fu_968_p3;
reg   [7:0] max_V_19_reg_1824;
reg   [7:0] p_Result_20_reg_1831;
wire   [7:0] max_V_2_fu_995_p3;
reg   [7:0] max_V_2_reg_1837;
wire   [7:0] max_V_11_fu_1011_p3;
reg   [7:0] max_V_11_reg_1844;
wire   [7:0] max_V_20_fu_1027_p3;
reg   [7:0] max_V_20_reg_1851;
wire   [23:0] src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return;
reg   [23:0] src_buf_V_1_1_reg_1858;
reg    ap_enable_reg_pp3_iter7;
wire   [7:0] max_V_3_fu_1049_p3;
reg   [7:0] max_V_3_reg_1863;
wire   [7:0] p_Result_4_fu_1055_p1;
reg   [7:0] p_Result_4_reg_1869;
wire   [0:0] icmp_ln878_9_fu_1059_p2;
reg   [0:0] icmp_ln878_9_reg_1874;
wire   [7:0] p_Result_5_fu_1065_p1;
reg   [7:0] p_Result_5_reg_1879;
wire   [7:0] max_V_12_fu_1091_p3;
reg   [7:0] max_V_12_reg_1885;
wire   [7:0] p_Result_13_fu_1097_p4;
reg   [7:0] p_Result_13_reg_1891;
wire   [0:0] icmp_ln878_17_fu_1107_p2;
reg   [0:0] icmp_ln878_17_reg_1896;
reg   [7:0] p_Result_14_reg_1901;
wire   [7:0] max_V_21_fu_1145_p3;
reg   [7:0] max_V_21_reg_1907;
wire   [7:0] p_Result_22_fu_1151_p4;
reg   [7:0] p_Result_22_reg_1913;
wire   [0:0] icmp_ln878_25_fu_1161_p2;
reg   [0:0] icmp_ln878_25_reg_1918;
reg   [7:0] p_Result_23_reg_1923;
wire   [7:0] max_V_5_fu_1200_p3;
reg   [7:0] max_V_5_reg_1929;
wire   [7:0] max_V_14_fu_1230_p3;
reg   [7:0] max_V_14_reg_1936;
wire   [7:0] max_V_23_fu_1260_p3;
reg   [7:0] max_V_23_reg_1943;
wire   [23:0] src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return;
reg   [23:0] src_buf_V_2_1_reg_1950;
reg    ap_enable_reg_pp3_iter9;
wire   [7:0] max_V_6_fu_1283_p3;
reg   [7:0] max_V_6_reg_1955;
wire   [7:0] p_Result_7_fu_1289_p1;
reg   [7:0] p_Result_7_reg_1961;
wire   [0:0] icmp_ln878_12_fu_1293_p2;
reg   [0:0] icmp_ln878_12_reg_1966;
wire   [7:0] p_Result_8_fu_1299_p1;
reg   [7:0] p_Result_8_reg_1971;
wire   [7:0] max_V_15_fu_1325_p3;
reg   [7:0] max_V_15_reg_1977;
wire   [7:0] p_Result_16_fu_1331_p4;
reg   [7:0] p_Result_16_reg_1983;
wire   [0:0] icmp_ln878_20_fu_1341_p2;
reg   [0:0] icmp_ln878_20_reg_1988;
reg   [7:0] p_Result_17_reg_1993;
wire   [7:0] max_V_24_fu_1379_p3;
reg   [7:0] max_V_24_reg_1999;
wire   [7:0] p_Result_25_fu_1385_p4;
reg   [7:0] p_Result_25_reg_2005;
wire   [0:0] icmp_ln878_28_fu_1395_p2;
reg   [0:0] icmp_ln878_28_reg_2010;
reg   [7:0] p_Result_26_reg_2015;
wire   [23:0] p_Result_27_fu_1501_p4;
reg   [23:0] p_Result_27_reg_2021;
wire   [12:0] row_V_1_fu_1511_p2;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state3;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
reg    ap_enable_reg_pp1_iter2;
wire    ap_CS_fsm_state7;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state8;
reg    ap_enable_reg_pp2_iter1;
reg    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_flush_enable;
reg    ap_enable_reg_pp3_iter2;
reg    ap_enable_reg_pp3_iter3;
reg    ap_enable_reg_pp3_iter6;
reg    ap_enable_reg_pp3_iter8;
reg    ap_enable_reg_pp3_iter10;
reg    ap_condition_pp3_exit_iter9_state21;
wire   [10:0] buf_V_0_address0;
reg    buf_V_0_ce0;
reg   [10:0] buf_V_0_address1;
reg    buf_V_0_ce1;
reg    buf_V_0_we1;
reg   [23:0] buf_V_0_d1;
wire   [10:0] buf_V_1_address0;
reg    buf_V_1_ce0;
reg   [10:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [23:0] buf_V_1_d1;
wire   [10:0] buf_V_2_address0;
reg    buf_V_2_ce0;
reg   [10:0] buf_V_2_address1;
reg    buf_V_2_ce1;
reg    buf_V_2_we1;
reg   [23:0] buf_V_2_d1;
wire    src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_ready;
wire    src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_ready;
wire    src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_ready;
wire   [1:0] ap_phi_mux_row_ind_V_1_phi_fu_340_p4;
reg   [1:0] row_ind_V_1_reg_336;
wire   [0:0] icmp_ln263_fu_591_p2;
reg   [12:0] ap_phi_mux_i_col_046_0_phi_fu_351_p4;
reg   [12:0] ap_phi_mux_i_col_V_0_phi_fu_363_p4;
wire    ap_block_pp2_stage0;
reg   [12:0] row_ind_V_2_reg_371;
reg   [12:0] row_ind_V_0_reg_392;
reg   [12:0] row_ind_V_1_1_reg_381;
reg   [12:0] row_V_reg_404;
reg   [12:0] ap_phi_mux_col_V_phi_fu_420_p4;
reg   [23:0] ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4;
reg   [23:0] ap_phi_mux_p_Val2_s_phi_fu_444_p4;
wire   [23:0] ap_phi_reg_pp3_iter0_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_reg_pp3_iter1_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_reg_pp3_iter2_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_reg_pp3_iter3_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_reg_pp3_iter4_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_reg_pp3_iter5_arrayidx486_i182255_load_0_2_reg_452;
reg   [23:0] ap_phi_mux_buf_cop_V_0_0_phi_fu_468_p4;
wire   [23:0] buf_cop_V_0_fu_812_p5;
reg   [23:0] ap_phi_reg_pp3_iter5_buf_cop_V_0_0_reg_464;
wire   [23:0] ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_464;
reg   [23:0] ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_464;
reg   [23:0] ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_464;
reg   [23:0] ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_464;
reg   [23:0] ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_464;
reg   [23:0] ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4;
reg   [23:0] ap_phi_mux_p_Val2_3_phi_fu_491_p4;
wire   [23:0] ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter6_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_reg_pp3_iter7_buf_cop_V_1_reg_499;
reg   [23:0] ap_phi_mux_p_Val2_6_phi_fu_514_p4;
reg   [23:0] ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4;
wire   [23:0] ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter7_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter8_buf_cop_V_2_reg_534;
reg   [23:0] ap_phi_reg_pp3_iter9_buf_cop_V_2_reg_534;
wire   [63:0] zext_ln534_fu_631_p1;
wire   [63:0] zext_ln534_1_fu_651_p1;
wire   [63:0] zext_ln534_3_fu_785_p1;
wire   [63:0] zext_ln534_2_fu_792_p1;
wire   [63:0] zext_ln1616_fu_799_p1;
reg   [12:0] row_ind_V_0_0_fu_126;
wire   [12:0] zext_ln301_fu_597_p1;
reg   [12:0] row_ind_V_1_0_fu_130;
reg   [12:0] row_ind_V_2_0_fu_134;
reg    ap_block_pp3_stage0_01001;
wire   [15:0] zext_ln878_fu_622_p1;
wire   [15:0] zext_ln878_1_fu_642_p1;
wire   [16:0] img_height_cast_fu_656_p1;
wire   [15:0] tmp_1_fu_670_p4;
wire   [16:0] zext_ln878_3_fu_735_p1;
wire   [15:0] zext_ln878_2_fu_731_p1;
wire   [13:0] zext_ln878_5_fu_771_p1;
wire   [15:0] zext_ln878_4_fu_767_p1;
wire   [7:0] p_Result_s_fu_829_p1;
wire   [7:0] p_Result_1_fu_840_p1;
wire   [7:0] max_V_fu_833_p3;
wire   [0:0] icmp_ln878_6_fu_844_p2;
wire   [7:0] select_ln56_fu_850_p3;
wire   [7:0] p_Result_9_fu_869_p4;
wire   [7:0] p_Result_10_fu_886_p4;
wire   [7:0] max_V_9_fu_879_p3;
wire   [0:0] icmp_ln878_14_fu_896_p2;
wire   [7:0] select_ln56_8_fu_902_p3;
wire   [7:0] p_Result_18_fu_927_p4;
wire   [7:0] p_Result_19_fu_944_p4;
wire   [7:0] max_V_18_fu_937_p3;
wire   [0:0] icmp_ln878_22_fu_954_p2;
wire   [7:0] select_ln56_16_fu_960_p3;
wire   [0:0] icmp_ln878_7_fu_985_p2;
wire   [7:0] select_ln56_1_fu_989_p3;
wire   [0:0] icmp_ln878_15_fu_1001_p2;
wire   [7:0] select_ln56_9_fu_1005_p3;
wire   [0:0] icmp_ln878_23_fu_1017_p2;
wire   [7:0] select_ln56_17_fu_1021_p3;
wire   [7:0] p_Result_3_fu_1033_p1;
wire   [0:0] icmp_ln878_8_fu_1037_p2;
wire   [7:0] select_ln56_2_fu_1042_p3;
wire   [7:0] p_Result_12_fu_1069_p4;
wire   [0:0] icmp_ln878_16_fu_1079_p2;
wire   [7:0] select_ln56_10_fu_1084_p3;
wire   [7:0] p_Result_21_fu_1123_p4;
wire   [0:0] icmp_ln878_24_fu_1133_p2;
wire   [7:0] select_ln56_18_fu_1138_p3;
wire   [7:0] select_ln56_3_fu_1177_p3;
wire   [7:0] max_V_4_fu_1182_p3;
wire   [0:0] icmp_ln878_10_fu_1188_p2;
wire   [7:0] select_ln56_4_fu_1193_p3;
wire   [7:0] select_ln56_11_fu_1207_p3;
wire   [7:0] max_V_13_fu_1212_p3;
wire   [0:0] icmp_ln878_18_fu_1218_p2;
wire   [7:0] select_ln56_12_fu_1223_p3;
wire   [7:0] select_ln56_19_fu_1237_p3;
wire   [7:0] max_V_22_fu_1242_p3;
wire   [0:0] icmp_ln878_26_fu_1248_p2;
wire   [7:0] select_ln56_20_fu_1253_p3;
wire   [7:0] p_Result_6_fu_1267_p1;
wire   [0:0] icmp_ln878_11_fu_1271_p2;
wire   [7:0] select_ln56_5_fu_1276_p3;
wire   [7:0] p_Result_15_fu_1303_p4;
wire   [0:0] icmp_ln878_19_fu_1313_p2;
wire   [7:0] select_ln56_13_fu_1318_p3;
wire   [7:0] p_Result_24_fu_1357_p4;
wire   [0:0] icmp_ln878_27_fu_1367_p2;
wire   [7:0] select_ln56_21_fu_1372_p3;
wire   [7:0] select_ln56_6_fu_1411_p3;
wire   [7:0] max_V_7_fu_1416_p3;
wire   [0:0] icmp_ln878_13_fu_1422_p2;
wire   [7:0] select_ln56_7_fu_1427_p3;
wire   [7:0] select_ln56_14_fu_1441_p3;
wire   [7:0] max_V_16_fu_1446_p3;
wire   [0:0] icmp_ln878_21_fu_1452_p2;
wire   [7:0] select_ln56_15_fu_1457_p3;
wire   [7:0] select_ln56_22_fu_1471_p3;
wire   [7:0] max_V_25_fu_1476_p3;
wire   [0:0] icmp_ln878_29_fu_1482_p2;
wire   [7:0] select_ln56_23_fu_1487_p3;
wire   [7:0] max_V_26_fu_1494_p3;
wire   [7:0] max_V_17_fu_1464_p3;
wire   [7:0] max_V_8_fu_1434_p3;
reg   [9:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_condition_652;
reg    ap_condition_288;
reg    ap_condition_86;
reg    ap_condition_165;
reg    ap_condition_1487;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter4 = 1'b0;
#0 ap_enable_reg_pp3_iter5 = 1'b0;
#0 ap_enable_reg_pp3_iter7 = 1'b0;
#0 ap_enable_reg_pp3_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter2 = 1'b0;
#0 ap_enable_reg_pp3_iter3 = 1'b0;
#0 ap_enable_reg_pp3_iter6 = 1'b0;
#0 ap_enable_reg_pp3_iter8 = 1'b0;
#0 ap_enable_reg_pp3_iter10 = 1'b0;
end

erode_accel_xferode_1080_1920_3_9_1_0_1921_3_3_s_buf_V_0 #(
    .DataWidth( 24 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_0_address0),
    .ce0(buf_V_0_ce0),
    .q0(buf_V_0_q0),
    .address1(buf_V_0_address1),
    .ce1(buf_V_0_ce1),
    .we1(buf_V_0_we1),
    .d1(buf_V_0_d1)
);

erode_accel_xferode_1080_1920_3_9_1_0_1921_3_3_s_buf_V_0 #(
    .DataWidth( 24 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

erode_accel_xferode_1080_1920_3_9_1_0_1921_3_3_s_buf_V_0 #(
    .DataWidth( 24 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_2_address0),
    .ce0(buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(buf_V_2_address1),
    .ce1(buf_V_2_ce1),
    .we1(buf_V_2_we1),
    .d1(buf_V_2_d1)
);

erode_accel_xfExtractPixels_1_9_15_s src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546(
    .ap_ready(src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_ready),
    .p_read1(ap_phi_mux_buf_cop_V_0_0_phi_fu_468_p4),
    .ap_return(src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return)
);

erode_accel_xfExtractPixels_1_9_15_s src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552(
    .ap_ready(src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_ready),
    .p_read1(ap_phi_reg_pp3_iter7_buf_cop_V_1_reg_499),
    .ap_return(src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return)
);

erode_accel_xfExtractPixels_1_9_15_s src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558(
    .ap_ready(src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_ready),
    .p_read1(ap_phi_reg_pp3_iter9_buf_cop_V_2_reg_534),
    .ap_return(src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return)
);

erode_accel_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U27(
    .din0(buf_V_0_load_reg_1770),
    .din1(buf_V_1_load_reg_1776),
    .din2(buf_V_2_load_reg_1782),
    .din3(trunc_ln138_reg_1728),
    .dout(buf_cop_V_0_fu_812_p5)
);

erode_accel_mux_32_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
mux_32_24_1_1_U28(
    .din0(buf_V_0_load_reg_1770),
    .din1(buf_V_1_load_reg_1776),
    .din2(buf_V_2_load_reg_1782),
    .din3(trunc_ln138_1_reg_1733),
    .dout(tmp_fu_821_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state4)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state8))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state8);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp3_flush_enable)) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp3_exit_iter9_state21)) begin
                ap_enable_reg_pp3_iter10 <= ap_enable_reg_pp3_iter8;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp3_iter10 <= ap_enable_reg_pp3_iter9;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter11 <= ap_enable_reg_pp3_iter10;
        end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
            ap_enable_reg_pp3_iter11 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter2 <= ap_enable_reg_pp3_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter3 <= ap_enable_reg_pp3_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter4 <= ap_enable_reg_pp3_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter5 <= ap_enable_reg_pp3_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter6 <= ap_enable_reg_pp3_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter7 <= ap_enable_reg_pp3_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter8 <= ap_enable_reg_pp3_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter9 <= ap_enable_reg_pp3_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if ((1'b1 == ap_condition_652)) begin
            ap_phi_reg_pp3_iter1_arrayidx486_i182255_load_0_2_reg_452 <= 24'd16777215;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_arrayidx486_i182255_load_0_2_reg_452 <= ap_phi_reg_pp3_iter0_arrayidx486_i182255_load_0_2_reg_452;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if (((icmp_ln878_5_fu_780_p2 == 1'd0) & (icmp_ln878_4_fu_775_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_464 <= 24'd16777215;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_464 <= ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_464;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if (((icmp_ln878_5_fu_780_p2 == 1'd0) & (icmp_ln878_4_fu_775_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_499 <= 24'd16777215;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if (((icmp_ln878_5_fu_780_p2 == 1'd0) & (icmp_ln878_4_fu_775_p2 == 1'd1))) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_534 <= 24'd16777215;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_534;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_165)) begin
        if ((1'b1 == ap_condition_86)) begin
            ap_phi_reg_pp3_iter2_arrayidx486_i182255_load_0_2_reg_452 <= img_in_419_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter2_arrayidx486_i182255_load_0_2_reg_452 <= ap_phi_reg_pp3_iter1_arrayidx486_i182255_load_0_2_reg_452;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        if (((icmp_ln878_5_reg_1747_pp3_iter4_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1))) begin
            ap_phi_reg_pp3_iter6_buf_cop_V_1_reg_499 <= tmp_fu_821_p5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter6_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1))) begin
        if (((icmp_ln878_5_reg_1747_pp3_iter4_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1))) begin
            ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter5_arrayidx486_i182255_load_0_2_reg_452;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_534;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_4_reg_1743 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_reg_416 <= col_V_1_reg_1738;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        col_V_reg_416 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_col_046_0_reg_347 <= 13'd0;
    end else if (((icmp_ln878_reg_1626 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_col_046_0_reg_347 <= add_ln691_reg_1621;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_col_V_0_reg_359 <= 13'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln878_1_reg_1635 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        i_col_V_0_reg_359 <= add_ln691_1_reg_1630;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter8 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter7_reg == 1'd1))) begin
        p_Val2_3_reg_487 <= src_buf_V_1_0_reg_475;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        p_Val2_3_reg_487 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter10 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter9_reg == 1'd1))) begin
        p_Val2_6_reg_510 <= src_buf_V_2_0_reg_521;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        p_Val2_6_reg_510 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter5_reg == 1'd1))) begin
        p_Val2_s_reg_440 <= src_buf_V_0_0_reg_428;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        p_Val2_s_reg_440 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        row_V_reg_404 <= row_V_1_fu_1511_p2;
    end else if (((icmp_ln878_2_fu_680_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        row_V_reg_404 <= 13'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        row_ind_V_0_reg_392 <= row_ind_V_1_1_reg_381;
    end else if (((icmp_ln878_2_fu_680_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        row_ind_V_0_reg_392 <= row_ind_V_0_0_load_reg_1603;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        row_ind_V_1_1_reg_381 <= row_ind_V_2_reg_371;
    end else if (((icmp_ln878_2_fu_680_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        row_ind_V_1_1_reg_381 <= row_ind_V_1_0_load_reg_1608;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln263_fu_591_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_1_reg_336 <= init_row_ind_fu_576_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_ind_V_1_reg_336 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        row_ind_V_2_reg_371 <= row_ind_V_0_reg_392;
    end else if (((icmp_ln878_2_fu_680_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        row_ind_V_2_reg_371 <= row_ind_V_2_0_load_reg_1613;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter5_reg == 1'd1))) begin
        src_buf_V_0_0_reg_428 <= src_buf_V_0_1_reg_1793;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        src_buf_V_0_0_reg_428 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter8 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter7_reg == 1'd1))) begin
        src_buf_V_1_0_reg_475 <= src_buf_V_1_1_reg_1858;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        src_buf_V_1_0_reg_475 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter10 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter9_reg == 1'd1))) begin
        src_buf_V_2_0_reg_521 <= src_buf_V_2_1_reg_1950;
    end else if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        src_buf_V_2_0_reg_521 <= 24'd16777215;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln1616_reg_1644 <= add_ln1616_fu_665_p2;
        icmp_ln878_2_reg_1649 <= icmp_ln878_2_fu_680_p2;
        op2_assign_reg_1639 <= op2_assign_fu_659_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln691_1_reg_1630 <= add_ln691_1_fu_636_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        add_ln691_reg_1621 <= add_ln691_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_464 <= ap_phi_reg_pp3_iter1_buf_cop_V_0_0_reg_464;
        ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter1_buf_cop_V_1_reg_499;
        ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter1_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1))) begin
        ap_phi_reg_pp3_iter3_arrayidx486_i182255_load_0_2_reg_452 <= ap_phi_reg_pp3_iter2_arrayidx486_i182255_load_0_2_reg_452;
        ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_464 <= ap_phi_reg_pp3_iter2_buf_cop_V_0_0_reg_464;
        ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter2_buf_cop_V_1_reg_499;
        ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter2_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        ap_phi_reg_pp3_iter4_arrayidx486_i182255_load_0_2_reg_452 <= ap_phi_reg_pp3_iter3_arrayidx486_i182255_load_0_2_reg_452;
        ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_464 <= ap_phi_reg_pp3_iter3_buf_cop_V_0_0_reg_464;
        ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter3_buf_cop_V_1_reg_499;
        ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter3_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter4 == 1'b1))) begin
        ap_phi_reg_pp3_iter5_arrayidx486_i182255_load_0_2_reg_452 <= ap_phi_reg_pp3_iter4_arrayidx486_i182255_load_0_2_reg_452;
        ap_phi_reg_pp3_iter5_buf_cop_V_0_0_reg_464 <= ap_phi_reg_pp3_iter4_buf_cop_V_0_0_reg_464;
        ap_phi_reg_pp3_iter5_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter4_buf_cop_V_1_reg_499;
        ap_phi_reg_pp3_iter5_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter4_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter6 == 1'b1))) begin
        ap_phi_reg_pp3_iter7_buf_cop_V_1_reg_499 <= ap_phi_reg_pp3_iter6_buf_cop_V_1_reg_499;
        ap_phi_reg_pp3_iter7_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter6_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter7 == 1'b1))) begin
        ap_phi_reg_pp3_iter8_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter7_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter8 == 1'b1))) begin
        ap_phi_reg_pp3_iter9_buf_cop_V_2_reg_534 <= ap_phi_reg_pp3_iter8_buf_cop_V_2_reg_534;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter4 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter3_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter3_reg == 1'd1))) begin
        buf_V_0_load_reg_1770 <= buf_V_0_q0;
        buf_V_1_load_reg_1776 <= buf_V_1_q0;
        buf_V_2_load_reg_1782 <= buf_V_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_3_fu_739_p2 == 1'd1) & (icmp_ln878_2_reg_1649 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        cmp_i_i127_i_reg_1720 <= cmp_i_i127_i_fu_744_p2;
        trunc_ln124_reg_1724 <= trunc_ln124_fu_749_p1;
        trunc_ln138_1_reg_1733 <= trunc_ln138_1_fu_757_p1;
        trunc_ln138_reg_1728 <= trunc_ln138_fu_753_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_1_reg_1738 <= col_V_1_fu_761_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        col_V_reg_416_pp3_iter1_reg <= col_V_reg_416;
        icmp_ln878_4_reg_1743 <= icmp_ln878_4_fu_775_p2;
        icmp_ln878_4_reg_1743_pp3_iter1_reg <= icmp_ln878_4_reg_1743;
        icmp_ln878_5_reg_1747_pp3_iter1_reg <= icmp_ln878_5_reg_1747;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp3_stage0_11001)) begin
        col_V_reg_416_pp3_iter2_reg <= col_V_reg_416_pp3_iter1_reg;
        icmp_ln878_4_reg_1743_pp3_iter2_reg <= icmp_ln878_4_reg_1743_pp3_iter1_reg;
        icmp_ln878_4_reg_1743_pp3_iter3_reg <= icmp_ln878_4_reg_1743_pp3_iter2_reg;
        icmp_ln878_4_reg_1743_pp3_iter4_reg <= icmp_ln878_4_reg_1743_pp3_iter3_reg;
        icmp_ln878_4_reg_1743_pp3_iter5_reg <= icmp_ln878_4_reg_1743_pp3_iter4_reg;
        icmp_ln878_4_reg_1743_pp3_iter6_reg <= icmp_ln878_4_reg_1743_pp3_iter5_reg;
        icmp_ln878_4_reg_1743_pp3_iter7_reg <= icmp_ln878_4_reg_1743_pp3_iter6_reg;
        icmp_ln878_4_reg_1743_pp3_iter8_reg <= icmp_ln878_4_reg_1743_pp3_iter7_reg;
        icmp_ln878_4_reg_1743_pp3_iter9_reg <= icmp_ln878_4_reg_1743_pp3_iter8_reg;
        icmp_ln878_5_reg_1747_pp3_iter2_reg <= icmp_ln878_5_reg_1747_pp3_iter1_reg;
        icmp_ln878_5_reg_1747_pp3_iter3_reg <= icmp_ln878_5_reg_1747_pp3_iter2_reg;
        icmp_ln878_5_reg_1747_pp3_iter4_reg <= icmp_ln878_5_reg_1747_pp3_iter3_reg;
        icmp_ln882_reg_1766_pp3_iter10_reg <= icmp_ln882_reg_1766_pp3_iter9_reg;
        icmp_ln882_reg_1766_pp3_iter4_reg <= icmp_ln882_reg_1766;
        icmp_ln882_reg_1766_pp3_iter5_reg <= icmp_ln882_reg_1766_pp3_iter4_reg;
        icmp_ln882_reg_1766_pp3_iter6_reg <= icmp_ln882_reg_1766_pp3_iter5_reg;
        icmp_ln882_reg_1766_pp3_iter7_reg <= icmp_ln882_reg_1766_pp3_iter6_reg;
        icmp_ln882_reg_1766_pp3_iter8_reg <= icmp_ln882_reg_1766_pp3_iter7_reg;
        icmp_ln882_reg_1766_pp3_iter9_reg <= icmp_ln882_reg_1766_pp3_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_reg_1593 <= empty_fu_572_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        i_col_046_0_reg_347_pp1_iter1_reg <= i_col_046_0_reg_347;
        icmp_ln878_reg_1626 <= icmp_ln878_fu_626_p2;
        icmp_ln878_reg_1626_pp1_iter1_reg <= icmp_ln878_reg_1626;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter8_reg == 1'd1) & (tobool_i_i_2114_1_reg_1702 == 1'd1))) begin
        icmp_ln878_12_reg_1966 <= icmp_ln878_12_fu_1293_p2;
        icmp_ln878_20_reg_1988 <= icmp_ln878_20_fu_1341_p2;
        icmp_ln878_28_reg_2010 <= icmp_ln878_28_fu_1395_p2;
        p_Result_16_reg_1983 <= {{ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4[15:8]}};
        p_Result_25_reg_2005 <= {{ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4[23:16]}};
        p_Result_7_reg_1961 <= p_Result_7_fu_1289_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter6_reg == 1'd1) & (tobool_i_i_1106_1_reg_1681 == 1'd1))) begin
        icmp_ln878_17_reg_1896 <= icmp_ln878_17_fu_1107_p2;
        icmp_ln878_25_reg_1918 <= icmp_ln878_25_fu_1161_p2;
        icmp_ln878_9_reg_1874 <= icmp_ln878_9_fu_1059_p2;
        p_Result_13_reg_1891 <= {{ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4[15:8]}};
        p_Result_22_reg_1913 <= {{ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4[23:16]}};
        p_Result_4_reg_1869 <= p_Result_4_fu_1055_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln878_1_reg_1635 <= icmp_ln878_1_fu_646_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_fu_775_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln878_5_reg_1747 <= icmp_ln878_5_fu_780_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter2_reg == 1'd1))) begin
        icmp_ln882_reg_1766 <= icmp_ln882_fu_806_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1))) begin
        max_V_10_reg_1811 <= max_V_10_fu_910_p3;
        max_V_19_reg_1824 <= max_V_19_fu_968_p3;
        max_V_1_reg_1798 <= max_V_1_fu_858_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter5_reg == 1'd1))) begin
        max_V_11_reg_1844 <= max_V_11_fu_1011_p3;
        max_V_20_reg_1851 <= max_V_20_fu_1027_p3;
        max_V_2_reg_1837 <= max_V_2_fu_995_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter6_reg == 1'd1))) begin
        max_V_12_reg_1885 <= max_V_12_fu_1091_p3;
        max_V_21_reg_1907 <= max_V_21_fu_1145_p3;
        max_V_3_reg_1863 <= max_V_3_fu_1049_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter7_reg == 1'd1))) begin
        max_V_14_reg_1936 <= max_V_14_fu_1230_p3;
        max_V_23_reg_1943 <= max_V_23_fu_1260_p3;
        max_V_5_reg_1929 <= max_V_5_fu_1200_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter8_reg == 1'd1))) begin
        max_V_15_reg_1977 <= max_V_15_fu_1325_p3;
        max_V_24_reg_1999 <= max_V_24_fu_1379_p3;
        max_V_6_reg_1955 <= max_V_6_fu_1283_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1) & (tobool_i_i_2135_reg_1667 == 1'd1))) begin
        p_Result_11_reg_1818 <= {{src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return[15:8]}};
        p_Result_20_reg_1831 <= {{src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return[23:16]}};
        p_Result_2_reg_1805 <= p_Result_2_fu_865_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter6_reg == 1'd1) & (tobool_i_i_1106_2_reg_1688 == 1'd1))) begin
        p_Result_14_reg_1901 <= {{src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return[15:8]}};
        p_Result_23_reg_1923 <= {{src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return[23:16]}};
        p_Result_5_reg_1879 <= p_Result_5_fu_1065_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter8_reg == 1'd1) & (tobool_i_i_2114_2_reg_1709 == 1'd1))) begin
        p_Result_17_reg_1993 <= {{src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return[15:8]}};
        p_Result_26_reg_2015 <= {{src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return[23:16]}};
        p_Result_8_reg_1971 <= p_Result_8_fu_1299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (icmp_ln878_4_reg_1743_pp3_iter9_reg == 1'd1))) begin
        p_Result_27_reg_2021 <= p_Result_27_fu_1501_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_predicate_op142_read_state13 == 1'b1)) | ((icmp_ln878_reg_1626 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        reg_564 <= img_in_419_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln263_fu_591_p2 == 1'd0) & (ap_phi_mux_row_ind_V_1_phi_fu_340_p4 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_0_0_fu_126[1 : 0] <= zext_ln301_fu_597_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_ind_V_0_0_load_reg_1603[1 : 0] <= row_ind_V_0_0_fu_126[1 : 0];
        row_ind_V_1_0_load_reg_1608[1 : 0] <= row_ind_V_1_0_fu_130[1 : 0];
        row_ind_V_2_0_load_reg_1613[1 : 0] <= row_ind_V_2_0_fu_134[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln263_fu_591_p2 == 1'd0) & (ap_phi_mux_row_ind_V_1_phi_fu_340_p4 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_1_0_fu_130[1 : 0] <= zext_ln301_fu_597_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_row_ind_V_1_phi_fu_340_p4 == 2'd1) & ~(ap_phi_mux_row_ind_V_1_phi_fu_340_p4 == 2'd0) & (icmp_ln263_fu_591_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        row_ind_V_2_0_fu_134[1 : 0] <= zext_ln301_fu_597_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter5 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1))) begin
        src_buf_V_0_1_reg_1793 <= src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter7 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter6_reg == 1'd1))) begin
        src_buf_V_1_1_reg_1858 <= src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter9 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter8_reg == 1'd1))) begin
        src_buf_V_2_1_reg_1950 <= src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln878_2_fu_680_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        tobool_i_i_1106_1_reg_1681 <= tobool_i_i_1106_1_fu_706_p2;
        tobool_i_i_1106_2_reg_1688 <= tobool_i_i_1106_2_fu_711_p2;
        tobool_i_i_1106_reg_1674 <= tobool_i_i_1106_fu_701_p2;
        tobool_i_i_1126_reg_1660 <= tobool_i_i_1126_fu_691_p2;
        tobool_i_i_2114_1_reg_1702 <= tobool_i_i_2114_1_fu_721_p2;
        tobool_i_i_2114_2_reg_1709 <= tobool_i_i_2114_2_fu_726_p2;
        tobool_i_i_2114_reg_1695 <= tobool_i_i_2114_fu_716_p2;
        tobool_i_i_2135_reg_1667 <= tobool_i_i_2135_fu_696_p2;
        tobool_i_i_reg_1653 <= tobool_i_i_fu_686_p2;
    end
end

always @ (*) begin
    if ((icmp_ln878_fu_626_p2 == 1'd0)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln878_1_fu_646_p2 == 1'd0)) begin
        ap_condition_pp2_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter8 == 1'b0) & (ap_enable_reg_pp3_iter9 == 1'b1))) begin
        ap_condition_pp3_exit_iter9_state21 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter9_state21 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_subdone) & (icmp_ln878_4_fu_775_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_condition_pp3_flush_enable = 1'b1;
    end else begin
        ap_condition_pp3_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state11) & ((icmp_ln878_3_fu_739_p2 == 1'd0) | (icmp_ln878_2_reg_1649 == 1'd1))) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter11 == 1'b0) & (ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter10 == 1'b0) & (ap_enable_reg_pp3_iter8 == 1'b0) & (ap_enable_reg_pp3_iter6 == 1'b0) & (ap_enable_reg_pp3_iter3 == 1'b0) & (ap_enable_reg_pp3_iter2 == 1'b0) & (ap_enable_reg_pp3_iter9 == 1'b0) & (ap_enable_reg_pp3_iter7 == 1'b0) & (ap_enable_reg_pp3_iter5 == 1'b0) & (ap_enable_reg_pp3_iter4 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln878_5_reg_1747_pp3_iter4_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter4_reg == 1'd1))) begin
        ap_phi_mux_buf_cop_V_0_0_phi_fu_468_p4 = buf_cop_V_0_fu_812_p5;
    end else begin
        ap_phi_mux_buf_cop_V_0_0_phi_fu_468_p4 = ap_phi_reg_pp3_iter5_buf_cop_V_0_0_reg_464;
    end
end

always @ (*) begin
    if (((icmp_ln878_4_reg_1743 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_col_V_phi_fu_420_p4 = col_V_1_reg_1738;
    end else begin
        ap_phi_mux_col_V_phi_fu_420_p4 = col_V_reg_416;
    end
end

always @ (*) begin
    if (((icmp_ln878_reg_1626 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_i_col_046_0_phi_fu_351_p4 = add_ln691_reg_1621;
    end else begin
        ap_phi_mux_i_col_046_0_phi_fu_351_p4 = i_col_046_0_reg_347;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln878_1_reg_1635 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_i_col_V_0_phi_fu_363_p4 = add_ln691_1_reg_1630;
    end else begin
        ap_phi_mux_i_col_V_0_phi_fu_363_p4 = i_col_V_0_reg_359;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter8 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter7_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_3_phi_fu_491_p4 = src_buf_V_1_0_reg_475;
    end else begin
        ap_phi_mux_p_Val2_3_phi_fu_491_p4 = p_Val2_3_reg_487;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter10 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter9_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_6_phi_fu_514_p4 = src_buf_V_2_0_reg_521;
    end else begin
        ap_phi_mux_p_Val2_6_phi_fu_514_p4 = p_Val2_6_reg_510;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter5_reg == 1'd1))) begin
        ap_phi_mux_p_Val2_s_phi_fu_444_p4 = src_buf_V_0_0_reg_428;
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_444_p4 = p_Val2_s_reg_440;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter6 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter5_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4 = src_buf_V_0_1_reg_1793;
    end else begin
        ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4 = src_buf_V_0_0_reg_428;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter8 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter7_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4 = src_buf_V_1_1_reg_1858;
    end else begin
        ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4 = src_buf_V_1_0_reg_475;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter10 == 1'b1) & (icmp_ln878_4_reg_1743_pp3_iter9_reg == 1'd1))) begin
        ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4 = src_buf_V_2_1_reg_1950;
    end else begin
        ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4 = src_buf_V_2_0_reg_521;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln878_3_fu_739_p2 == 1'd0) | (icmp_ln878_2_reg_1649 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0))) begin
        buf_V_0_address1 = zext_ln534_2_fu_792_p1;
    end else if (((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0))) begin
        buf_V_0_address1 = zext_ln534_3_fu_785_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        buf_V_0_address1 = zext_ln534_1_fu_651_p1;
    end else begin
        buf_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        buf_V_0_ce0 = 1'b1;
    end else begin
        buf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0)) | ((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        buf_V_0_ce1 = 1'b1;
    end else begin
        buf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0))) begin
        buf_V_0_d1 = reg_564;
    end else if ((((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0)) | ((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        buf_V_0_d1 = 24'd16777215;
    end else begin
        buf_V_0_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0)) | ((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln878_1_reg_1635 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        buf_V_0_we1 = 1'b1;
    end else begin
        buf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1))) begin
        buf_V_1_address1 = zext_ln534_2_fu_792_p1;
    end else if (((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1))) begin
        buf_V_1_address1 = zext_ln534_3_fu_785_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        buf_V_1_address1 = zext_ln534_fu_631_p1;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        buf_V_1_ce0 = 1'b1;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1)) | ((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        buf_V_1_ce1 = 1'b1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1))) begin
        buf_V_1_d1 = 24'd16777215;
    end else if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1)) | ((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        buf_V_1_d1 = reg_564;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1)) | ((cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1) & (trunc_ln124_reg_1724 == 2'd1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln878_reg_1626_pp1_iter1_reg == 1'd1)))) begin
        buf_V_1_we1 = 1'b1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1487)) begin
        if ((cmp_i_i127_i_reg_1720 == 1'd1)) begin
            buf_V_2_address1 = zext_ln534_2_fu_792_p1;
        end else if ((cmp_i_i127_i_reg_1720 == 1'd0)) begin
            buf_V_2_address1 = zext_ln534_3_fu_785_p1;
        end else begin
            buf_V_2_address1 = 'bx;
        end
    end else begin
        buf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter3 == 1'b1))) begin
        buf_V_2_ce0 = 1'b1;
    end else begin
        buf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(trunc_ln124_reg_1724 == 2'd0) & ~(trunc_ln124_reg_1724 == 2'd1) & (cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1)) | (~(trunc_ln124_reg_1724 == 2'd0) & ~(trunc_ln124_reg_1724 == 2'd1) & (cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1)))) begin
        buf_V_2_ce1 = 1'b1;
    end else begin
        buf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1487)) begin
        if ((cmp_i_i127_i_reg_1720 == 1'd1)) begin
            buf_V_2_d1 = reg_564;
        end else if ((cmp_i_i127_i_reg_1720 == 1'd0)) begin
            buf_V_2_d1 = 24'd16777215;
        end else begin
            buf_V_2_d1 = 'bx;
        end
    end else begin
        buf_V_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln124_reg_1724 == 2'd0) & ~(trunc_ln124_reg_1724 == 2'd1) & (cmp_i_i127_i_reg_1720 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1)) | (~(trunc_ln124_reg_1724 == 2'd0) & ~(trunc_ln124_reg_1724 == 2'd1) & (cmp_i_i127_i_reg_1720 == 1'd0) & (1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1)))) begin
        buf_V_2_we1 = 1'b1;
    end else begin
        buf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((((cmp_i_i127_i_reg_1720 == 1'd1) & (icmp_ln878_5_reg_1747 == 1'd1) & (icmp_ln878_4_reg_1743 == 1'd1) & (ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0)) | ((icmp_ln878_reg_1626 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        img_in_419_blk_n = img_in_419_empty_n;
    end else begin
        img_in_419_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0) & (ap_predicate_op142_read_state13 == 1'b1)) | ((icmp_ln878_reg_1626 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        img_in_419_read = 1'b1;
    end else begin
        img_in_419_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (ap_enable_reg_pp3_iter11 == 1'b1) & (1'b0 == ap_block_pp3_stage0))) begin
        img_out_420_blk_n = img_out_420_full_n;
    end else begin
        img_out_420_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (ap_enable_reg_pp3_iter11 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        img_out_420_write = 1'b1;
    end else begin
        img_out_420_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln263_fu_591_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln878_fu_626_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln878_fu_626_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln878_1_fu_646_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln878_1_fu_646_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & ((icmp_ln878_3_fu_739_p2 == 1'd0) | (icmp_ln878_2_reg_1649 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter10 == 1'b0) & (ap_enable_reg_pp3_iter8 == 1'b0) & (ap_enable_reg_pp3_iter9 == 1'b1)) & ~((ap_enable_reg_pp3_iter11 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter10 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if ((((ap_enable_reg_pp3_iter11 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter10 == 1'b0)) | ((1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter10 == 1'b0) & (ap_enable_reg_pp3_iter8 == 1'b0) & (ap_enable_reg_pp3_iter9 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1616_fu_665_p2 = (empty_reg_1593 + 14'd1);

assign add_ln691_1_fu_636_p2 = (ap_phi_mux_i_col_V_0_phi_fu_363_p4 + 13'd1);

assign add_ln691_fu_616_p2 = (ap_phi_mux_i_col_046_0_phi_fu_351_p4 + 13'd1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((icmp_ln878_reg_1626 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((icmp_ln878_reg_1626 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp3_stage0_01001 = (((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (ap_enable_reg_pp3_iter11 == 1'b1) & (img_out_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op142_read_state13 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_11001 = (((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (ap_enable_reg_pp3_iter11 == 1'b1) & (img_out_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op142_read_state13 == 1'b1)));
end

always @ (*) begin
    ap_block_pp3_stage0_subdone = (((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (ap_enable_reg_pp3_iter11 == 1'b1) & (img_out_420_full_n == 1'b0)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (img_in_419_empty_n == 1'b0) & (ap_predicate_op142_read_state13 == 1'b1)));
end

assign ap_block_state12_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_pp3_stage0_iter1 = ((img_in_419_empty_n == 1'b0) & (ap_predicate_op142_read_state13 == 1'b1));
end

assign ap_block_state14_pp3_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp3_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp3_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp3_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp3_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp3_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp3_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp3_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp3_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state23_pp3_stage0_iter11 = ((icmp_ln882_reg_1766_pp3_iter10_reg == 1'd0) & (img_out_420_full_n == 1'b0));
end

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp1_stage0_iter1 = ((icmp_ln878_reg_1626 == 1'd1) & (img_in_419_empty_n == 1'b0));
end

assign ap_block_state6_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1487 = (~(trunc_ln124_reg_1724 == 2'd0) & ~(trunc_ln124_reg_1724 == 2'd1) & (1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter2 == 1'b1) & (icmp_ln878_5_reg_1747_pp3_iter1_reg == 1'd1) & (icmp_ln878_4_reg_1743_pp3_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_condition_165 = ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0));
end

always @ (*) begin
    ap_condition_288 = ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0));
end

always @ (*) begin
    ap_condition_652 = ((cmp_i_i127_i_reg_1720 == 1'd0) & (icmp_ln878_5_fu_780_p2 == 1'd1) & (icmp_ln878_4_fu_775_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_86 = ((cmp_i_i127_i_reg_1720 == 1'd1) & (icmp_ln878_5_reg_1747 == 1'd1) & (icmp_ln878_4_reg_1743 == 1'd1));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_phi_mux_row_ind_V_1_phi_fu_340_p4 = row_ind_V_1_reg_336;

assign ap_phi_reg_pp3_iter0_arrayidx486_i182255_load_0_2_reg_452 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_0_0_reg_464 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_1_reg_499 = 'bx;

assign ap_phi_reg_pp3_iter0_buf_cop_V_2_reg_534 = 'bx;

always @ (*) begin
    ap_predicate_op142_read_state13 = ((cmp_i_i127_i_reg_1720 == 1'd1) & (icmp_ln878_5_reg_1747 == 1'd1) & (icmp_ln878_4_reg_1743 == 1'd1));
end

assign buf_V_0_address0 = zext_ln1616_fu_799_p1;

assign buf_V_1_address0 = zext_ln1616_fu_799_p1;

assign buf_V_2_address0 = zext_ln1616_fu_799_p1;

assign cmp_i_i127_i_fu_744_p2 = ((zext_ln878_2_fu_731_p1 < img_height) ? 1'b1 : 1'b0);

assign col_V_1_fu_761_p2 = (ap_phi_mux_col_V_phi_fu_420_p4 + 13'd1);

assign empty_fu_572_p1 = img_width[13:0];

assign icmp_ln263_fu_591_p2 = ((row_ind_V_1_reg_336 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln878_10_fu_1188_p2 = ((p_Result_5_reg_1879 < max_V_4_fu_1182_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_11_fu_1271_p2 = ((p_Result_6_fu_1267_p1 < max_V_5_reg_1929) ? 1'b1 : 1'b0);

assign icmp_ln878_12_fu_1293_p2 = ((p_Result_7_fu_1289_p1 < max_V_6_fu_1283_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_13_fu_1422_p2 = ((p_Result_8_reg_1971 < max_V_7_fu_1416_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_14_fu_896_p2 = ((p_Result_10_fu_886_p4 < max_V_9_fu_879_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_15_fu_1001_p2 = ((p_Result_11_reg_1818 < max_V_10_reg_1811) ? 1'b1 : 1'b0);

assign icmp_ln878_16_fu_1079_p2 = ((p_Result_12_fu_1069_p4 < max_V_11_reg_1844) ? 1'b1 : 1'b0);

assign icmp_ln878_17_fu_1107_p2 = ((p_Result_13_fu_1097_p4 < max_V_12_fu_1091_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_18_fu_1218_p2 = ((p_Result_14_reg_1901 < max_V_13_fu_1212_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_19_fu_1313_p2 = ((p_Result_15_fu_1303_p4 < max_V_14_reg_1936) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_646_p2 = ((zext_ln878_1_fu_642_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln878_20_fu_1341_p2 = ((p_Result_16_fu_1331_p4 < max_V_15_fu_1325_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_21_fu_1452_p2 = ((p_Result_17_reg_1993 < max_V_16_fu_1446_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_22_fu_954_p2 = ((p_Result_19_fu_944_p4 < max_V_18_fu_937_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_23_fu_1017_p2 = ((p_Result_20_reg_1831 < max_V_19_reg_1824) ? 1'b1 : 1'b0);

assign icmp_ln878_24_fu_1133_p2 = ((p_Result_21_fu_1123_p4 < max_V_20_reg_1851) ? 1'b1 : 1'b0);

assign icmp_ln878_25_fu_1161_p2 = ((p_Result_22_fu_1151_p4 < max_V_21_fu_1145_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_26_fu_1248_p2 = ((p_Result_23_reg_1923 < max_V_22_fu_1242_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_27_fu_1367_p2 = ((p_Result_24_fu_1357_p4 < max_V_23_reg_1943) ? 1'b1 : 1'b0);

assign icmp_ln878_28_fu_1395_p2 = ((p_Result_25_fu_1385_p4 < max_V_24_fu_1379_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_29_fu_1482_p2 = ((p_Result_26_reg_2015 < max_V_25_fu_1476_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_680_p2 = ((tmp_1_fu_670_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_739_p2 = ((zext_ln878_3_fu_735_p1 < op2_assign_reg_1639) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_775_p2 = ((zext_ln878_5_fu_771_p1 < add_ln1616_reg_1644) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_780_p2 = ((zext_ln878_4_fu_767_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln878_6_fu_844_p2 = ((p_Result_1_fu_840_p1 < max_V_fu_833_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_7_fu_985_p2 = ((p_Result_2_reg_1805 < max_V_1_reg_1798) ? 1'b1 : 1'b0);

assign icmp_ln878_8_fu_1037_p2 = ((p_Result_3_fu_1033_p1 < max_V_2_reg_1837) ? 1'b1 : 1'b0);

assign icmp_ln878_9_fu_1059_p2 = ((p_Result_4_fu_1055_p1 < max_V_3_fu_1049_p3) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_626_p2 = ((zext_ln878_fu_622_p1 < img_width) ? 1'b1 : 1'b0);

assign icmp_ln882_fu_806_p2 = ((col_V_reg_416_pp3_iter2_reg == 13'd0) ? 1'b1 : 1'b0);

assign img_height_cast_fu_656_p1 = img_height;

assign img_out_420_din = p_Result_27_reg_2021;

assign init_row_ind_fu_576_p2 = (row_ind_V_1_reg_336 + 2'd1);

assign max_V_10_fu_910_p3 = ((tobool_i_i_1126_reg_1660[0:0] == 1'b1) ? select_ln56_8_fu_902_p3 : max_V_9_fu_879_p3);

assign max_V_11_fu_1011_p3 = ((tobool_i_i_2135_reg_1667[0:0] == 1'b1) ? select_ln56_9_fu_1005_p3 : max_V_10_reg_1811);

assign max_V_12_fu_1091_p3 = ((tobool_i_i_1106_reg_1674[0:0] == 1'b1) ? select_ln56_10_fu_1084_p3 : max_V_11_reg_1844);

assign max_V_13_fu_1212_p3 = ((tobool_i_i_1106_1_reg_1681[0:0] == 1'b1) ? select_ln56_11_fu_1207_p3 : max_V_12_reg_1885);

assign max_V_14_fu_1230_p3 = ((tobool_i_i_1106_2_reg_1688[0:0] == 1'b1) ? select_ln56_12_fu_1223_p3 : max_V_13_fu_1212_p3);

assign max_V_15_fu_1325_p3 = ((tobool_i_i_2114_reg_1695[0:0] == 1'b1) ? select_ln56_13_fu_1318_p3 : max_V_14_reg_1936);

assign max_V_16_fu_1446_p3 = ((tobool_i_i_2114_1_reg_1702[0:0] == 1'b1) ? select_ln56_14_fu_1441_p3 : max_V_15_reg_1977);

assign max_V_17_fu_1464_p3 = ((tobool_i_i_2114_2_reg_1709[0:0] == 1'b1) ? select_ln56_15_fu_1457_p3 : max_V_16_fu_1446_p3);

assign max_V_18_fu_937_p3 = ((tobool_i_i_reg_1653[0:0] == 1'b1) ? p_Result_18_fu_927_p4 : 8'd255);

assign max_V_19_fu_968_p3 = ((tobool_i_i_1126_reg_1660[0:0] == 1'b1) ? select_ln56_16_fu_960_p3 : max_V_18_fu_937_p3);

assign max_V_1_fu_858_p3 = ((tobool_i_i_1126_reg_1660[0:0] == 1'b1) ? select_ln56_fu_850_p3 : max_V_fu_833_p3);

assign max_V_20_fu_1027_p3 = ((tobool_i_i_2135_reg_1667[0:0] == 1'b1) ? select_ln56_17_fu_1021_p3 : max_V_19_reg_1824);

assign max_V_21_fu_1145_p3 = ((tobool_i_i_1106_reg_1674[0:0] == 1'b1) ? select_ln56_18_fu_1138_p3 : max_V_20_reg_1851);

assign max_V_22_fu_1242_p3 = ((tobool_i_i_1106_1_reg_1681[0:0] == 1'b1) ? select_ln56_19_fu_1237_p3 : max_V_21_reg_1907);

assign max_V_23_fu_1260_p3 = ((tobool_i_i_1106_2_reg_1688[0:0] == 1'b1) ? select_ln56_20_fu_1253_p3 : max_V_22_fu_1242_p3);

assign max_V_24_fu_1379_p3 = ((tobool_i_i_2114_reg_1695[0:0] == 1'b1) ? select_ln56_21_fu_1372_p3 : max_V_23_reg_1943);

assign max_V_25_fu_1476_p3 = ((tobool_i_i_2114_1_reg_1702[0:0] == 1'b1) ? select_ln56_22_fu_1471_p3 : max_V_24_reg_1999);

assign max_V_26_fu_1494_p3 = ((tobool_i_i_2114_2_reg_1709[0:0] == 1'b1) ? select_ln56_23_fu_1487_p3 : max_V_25_fu_1476_p3);

assign max_V_2_fu_995_p3 = ((tobool_i_i_2135_reg_1667[0:0] == 1'b1) ? select_ln56_1_fu_989_p3 : max_V_1_reg_1798);

assign max_V_3_fu_1049_p3 = ((tobool_i_i_1106_reg_1674[0:0] == 1'b1) ? select_ln56_2_fu_1042_p3 : max_V_2_reg_1837);

assign max_V_4_fu_1182_p3 = ((tobool_i_i_1106_1_reg_1681[0:0] == 1'b1) ? select_ln56_3_fu_1177_p3 : max_V_3_reg_1863);

assign max_V_5_fu_1200_p3 = ((tobool_i_i_1106_2_reg_1688[0:0] == 1'b1) ? select_ln56_4_fu_1193_p3 : max_V_4_fu_1182_p3);

assign max_V_6_fu_1283_p3 = ((tobool_i_i_2114_reg_1695[0:0] == 1'b1) ? select_ln56_5_fu_1276_p3 : max_V_5_reg_1929);

assign max_V_7_fu_1416_p3 = ((tobool_i_i_2114_1_reg_1702[0:0] == 1'b1) ? select_ln56_6_fu_1411_p3 : max_V_6_reg_1955);

assign max_V_8_fu_1434_p3 = ((tobool_i_i_2114_2_reg_1709[0:0] == 1'b1) ? select_ln56_7_fu_1427_p3 : max_V_7_fu_1416_p3);

assign max_V_9_fu_879_p3 = ((tobool_i_i_reg_1653[0:0] == 1'b1) ? p_Result_9_fu_869_p4 : 8'd255);

assign max_V_fu_833_p3 = ((tobool_i_i_reg_1653[0:0] == 1'b1) ? p_Result_s_fu_829_p1 : 8'd255);

assign op2_assign_fu_659_p2 = (img_height_cast_fu_656_p1 + 17'd1);

assign p_Result_10_fu_886_p4 = {{ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4[15:8]}};

assign p_Result_12_fu_1069_p4 = {{ap_phi_mux_p_Val2_3_phi_fu_491_p4[15:8]}};

assign p_Result_13_fu_1097_p4 = {{ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4[15:8]}};

assign p_Result_15_fu_1303_p4 = {{ap_phi_mux_p_Val2_6_phi_fu_514_p4[15:8]}};

assign p_Result_16_fu_1331_p4 = {{ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4[15:8]}};

assign p_Result_18_fu_927_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_444_p4[23:16]}};

assign p_Result_19_fu_944_p4 = {{ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4[23:16]}};

assign p_Result_1_fu_840_p1 = ap_phi_mux_src_buf_V_0_0_phi_fu_432_p4[7:0];

assign p_Result_21_fu_1123_p4 = {{ap_phi_mux_p_Val2_3_phi_fu_491_p4[23:16]}};

assign p_Result_22_fu_1151_p4 = {{ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4[23:16]}};

assign p_Result_24_fu_1357_p4 = {{ap_phi_mux_p_Val2_6_phi_fu_514_p4[23:16]}};

assign p_Result_25_fu_1385_p4 = {{ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4[23:16]}};

assign p_Result_27_fu_1501_p4 = {{{max_V_26_fu_1494_p3}, {max_V_17_fu_1464_p3}}, {max_V_8_fu_1434_p3}};

assign p_Result_2_fu_865_p1 = src_buf_V_0_1_xfExtractPixels_1_9_15_s_fu_546_ap_return[7:0];

assign p_Result_3_fu_1033_p1 = ap_phi_mux_p_Val2_3_phi_fu_491_p4[7:0];

assign p_Result_4_fu_1055_p1 = ap_phi_mux_src_buf_V_1_0_phi_fu_479_p4[7:0];

assign p_Result_5_fu_1065_p1 = src_buf_V_1_1_xfExtractPixels_1_9_15_s_fu_552_ap_return[7:0];

assign p_Result_6_fu_1267_p1 = ap_phi_mux_p_Val2_6_phi_fu_514_p4[7:0];

assign p_Result_7_fu_1289_p1 = ap_phi_mux_src_buf_V_2_0_phi_fu_526_p4[7:0];

assign p_Result_8_fu_1299_p1 = src_buf_V_2_1_xfExtractPixels_1_9_15_s_fu_558_ap_return[7:0];

assign p_Result_9_fu_869_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_444_p4[15:8]}};

assign p_Result_s_fu_829_p1 = ap_phi_mux_p_Val2_s_phi_fu_444_p4[7:0];

assign row_V_1_fu_1511_p2 = (row_V_reg_404 + 13'd1);

assign select_ln56_10_fu_1084_p3 = ((icmp_ln878_16_fu_1079_p2[0:0] == 1'b1) ? p_Result_12_fu_1069_p4 : max_V_11_reg_1844);

assign select_ln56_11_fu_1207_p3 = ((icmp_ln878_17_reg_1896[0:0] == 1'b1) ? p_Result_13_reg_1891 : max_V_12_reg_1885);

assign select_ln56_12_fu_1223_p3 = ((icmp_ln878_18_fu_1218_p2[0:0] == 1'b1) ? p_Result_14_reg_1901 : max_V_13_fu_1212_p3);

assign select_ln56_13_fu_1318_p3 = ((icmp_ln878_19_fu_1313_p2[0:0] == 1'b1) ? p_Result_15_fu_1303_p4 : max_V_14_reg_1936);

assign select_ln56_14_fu_1441_p3 = ((icmp_ln878_20_reg_1988[0:0] == 1'b1) ? p_Result_16_reg_1983 : max_V_15_reg_1977);

assign select_ln56_15_fu_1457_p3 = ((icmp_ln878_21_fu_1452_p2[0:0] == 1'b1) ? p_Result_17_reg_1993 : max_V_16_fu_1446_p3);

assign select_ln56_16_fu_960_p3 = ((icmp_ln878_22_fu_954_p2[0:0] == 1'b1) ? p_Result_19_fu_944_p4 : max_V_18_fu_937_p3);

assign select_ln56_17_fu_1021_p3 = ((icmp_ln878_23_fu_1017_p2[0:0] == 1'b1) ? p_Result_20_reg_1831 : max_V_19_reg_1824);

assign select_ln56_18_fu_1138_p3 = ((icmp_ln878_24_fu_1133_p2[0:0] == 1'b1) ? p_Result_21_fu_1123_p4 : max_V_20_reg_1851);

assign select_ln56_19_fu_1237_p3 = ((icmp_ln878_25_reg_1918[0:0] == 1'b1) ? p_Result_22_reg_1913 : max_V_21_reg_1907);

assign select_ln56_1_fu_989_p3 = ((icmp_ln878_7_fu_985_p2[0:0] == 1'b1) ? p_Result_2_reg_1805 : max_V_1_reg_1798);

assign select_ln56_20_fu_1253_p3 = ((icmp_ln878_26_fu_1248_p2[0:0] == 1'b1) ? p_Result_23_reg_1923 : max_V_22_fu_1242_p3);

assign select_ln56_21_fu_1372_p3 = ((icmp_ln878_27_fu_1367_p2[0:0] == 1'b1) ? p_Result_24_fu_1357_p4 : max_V_23_reg_1943);

assign select_ln56_22_fu_1471_p3 = ((icmp_ln878_28_reg_2010[0:0] == 1'b1) ? p_Result_25_reg_2005 : max_V_24_reg_1999);

assign select_ln56_23_fu_1487_p3 = ((icmp_ln878_29_fu_1482_p2[0:0] == 1'b1) ? p_Result_26_reg_2015 : max_V_25_fu_1476_p3);

assign select_ln56_2_fu_1042_p3 = ((icmp_ln878_8_fu_1037_p2[0:0] == 1'b1) ? p_Result_3_fu_1033_p1 : max_V_2_reg_1837);

assign select_ln56_3_fu_1177_p3 = ((icmp_ln878_9_reg_1874[0:0] == 1'b1) ? p_Result_4_reg_1869 : max_V_3_reg_1863);

assign select_ln56_4_fu_1193_p3 = ((icmp_ln878_10_fu_1188_p2[0:0] == 1'b1) ? p_Result_5_reg_1879 : max_V_4_fu_1182_p3);

assign select_ln56_5_fu_1276_p3 = ((icmp_ln878_11_fu_1271_p2[0:0] == 1'b1) ? p_Result_6_fu_1267_p1 : max_V_5_reg_1929);

assign select_ln56_6_fu_1411_p3 = ((icmp_ln878_12_reg_1966[0:0] == 1'b1) ? p_Result_7_reg_1961 : max_V_6_reg_1955);

assign select_ln56_7_fu_1427_p3 = ((icmp_ln878_13_fu_1422_p2[0:0] == 1'b1) ? p_Result_8_reg_1971 : max_V_7_fu_1416_p3);

assign select_ln56_8_fu_902_p3 = ((icmp_ln878_14_fu_896_p2[0:0] == 1'b1) ? p_Result_10_fu_886_p4 : max_V_9_fu_879_p3);

assign select_ln56_9_fu_1005_p3 = ((icmp_ln878_15_fu_1001_p2[0:0] == 1'b1) ? p_Result_11_reg_1818 : max_V_10_reg_1811);

assign select_ln56_fu_850_p3 = ((icmp_ln878_6_fu_844_p2[0:0] == 1'b1) ? p_Result_1_fu_840_p1 : max_V_fu_833_p3);

assign tmp_1_fu_670_p4 = {{op2_assign_fu_659_p2[16:1]}};

assign tobool_i_i_1106_1_fu_706_p2 = ((p_read4 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1106_2_fu_711_p2 = ((p_read5 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1106_fu_701_p2 = ((p_read3 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_1126_fu_691_p2 = ((p_read1 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2114_1_fu_721_p2 = ((p_read7 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2114_2_fu_726_p2 = ((p_read8 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2114_fu_716_p2 = ((p_read6 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_2135_fu_696_p2 = ((p_read2 != 8'd0) ? 1'b1 : 1'b0);

assign tobool_i_i_fu_686_p2 = ((p_read != 8'd0) ? 1'b1 : 1'b0);

assign trunc_ln124_fu_749_p1 = row_ind_V_2_reg_371[1:0];

assign trunc_ln138_1_fu_757_p1 = row_ind_V_1_1_reg_381[1:0];

assign trunc_ln138_fu_753_p1 = row_ind_V_0_reg_392[1:0];

assign zext_ln1616_fu_799_p1 = col_V_reg_416_pp3_iter2_reg;

assign zext_ln301_fu_597_p1 = row_ind_V_1_reg_336;

assign zext_ln534_1_fu_651_p1 = i_col_V_0_reg_359;

assign zext_ln534_2_fu_792_p1 = col_V_reg_416_pp3_iter1_reg;

assign zext_ln534_3_fu_785_p1 = col_V_reg_416_pp3_iter1_reg;

assign zext_ln534_fu_631_p1 = i_col_046_0_reg_347_pp1_iter1_reg;

assign zext_ln878_1_fu_642_p1 = ap_phi_mux_i_col_V_0_phi_fu_363_p4;

assign zext_ln878_2_fu_731_p1 = row_V_reg_404;

assign zext_ln878_3_fu_735_p1 = row_V_reg_404;

assign zext_ln878_4_fu_767_p1 = ap_phi_mux_col_V_phi_fu_420_p4;

assign zext_ln878_5_fu_771_p1 = ap_phi_mux_col_V_phi_fu_420_p4;

assign zext_ln878_fu_622_p1 = ap_phi_mux_i_col_046_0_phi_fu_351_p4;

always @ (posedge ap_clk) begin
    row_ind_V_0_0_load_reg_1603[12:2] <= 11'b00000000000;
    row_ind_V_1_0_load_reg_1608[12:2] <= 11'b00000000000;
    row_ind_V_2_0_load_reg_1613[12:2] <= 11'b00000000000;
    row_ind_V_0_0_fu_126[12:2] <= 11'b00000000000;
    row_ind_V_1_0_fu_130[12:2] <= 11'b00000000000;
    row_ind_V_2_0_fu_134[12:2] <= 11'b00000000000;
end

endmodule //erode_accel_xferode_1080_1920_3_9_1_0_1921_3_3_s
