// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2.2 (64-bit)
// Version: 2020.2.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cornerHarris_accel_xFSuppressionRad1_1_5_ap_uint_8_s (
        ap_ready,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        ap_return
);


output   ap_ready;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
output  [0:0] ap_return;

wire    Max_xFFindMaxRad1_ap_int_32_s_fu_44_ap_ready;
wire   [0:0] Max_xFFindMaxRad1_ap_int_32_s_fu_44_ap_return;

cornerHarris_accel_xFFindMaxRad1_ap_int_32_s Max_xFFindMaxRad1_ap_int_32_s_fu_44(
    .ap_ready(Max_xFFindMaxRad1_ap_int_32_s_fu_44_ap_ready),
    .t1(p_read1),
    .m0(p_read2),
    .m1(p_read3),
    .m2(p_read4),
    .b1(p_read5),
    .ap_return(Max_xFFindMaxRad1_ap_int_32_s_fu_44_ap_return)
);

assign ap_ready = 1'b1;

assign ap_return = Max_xFFindMaxRad1_ap_int_32_s_fu_44_ap_return;

endmodule //cornerHarris_accel_xFSuppressionRad1_1_5_ap_uint_8_s
